### ISSUE TITLE
Hilghight the road in locator

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2-C040#109]
### Description
Use a more visible style for road found in locator (Openlayers has a thin green line as default, it should be more similar to the leaflet one) 
![image](https://user-images.githubusercontent.com/1279510/33880343-a30553dc-df31-11e7-83b4-4f919c72c070.png)
Should be more similar to this, instead: 
![image](https://user-images.githubusercontent.com/1279510/33880436-e36d3c46-df31-11e7-80f6-678bd9945594.png)

### Please indicate if this issue is related to a bug or a new feature request
- [x] New Feature

### In case of New Feature (otherwise remove this paragraph)

*Acceptance Criteria - AC*

- The road should be more visible (electric blue suggested by the customer) 

connected to geosolutions-it/MapStore2#1506

**Comment by allyoucanmap** [comment]
geosolutions-it/MapStore2/#2771
