### ISSUE TITLE
Add automatic layer refresh tool

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2-C040#114]
### Description
Riportare il plugin ‘layer refresh’ per la sincronizzazione del layer (gxp_synchlayerenable)

### Please indicate if this issue is related to a bug or a new feature request
- [ ] Bug
- [x] New Feature

### In case of New Feature (otherwise remove this paragraph)

*Acceptance Criteria - AC*

- MapStore should provide a tool to auto-refrsh layers (see MapStore1 gxp_synchlayerenable)

**Comment by simboss** [comment]
Since this is a new feature that impacts the GUI as well, I would want to see a mockup and a small description of this new functionality would work for the end user.

This _must_ be done before doing the work.

**Comment by tdipisa** [comment]
closed for inactivity
