### ISSUE TITLE
Solve issues and add improvements to widgets

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2-C040#118]
### Description
We should port widgets improvements and bug fixes from MS2 to this project. Solve issues with backend process too. 

### Depends On (optional)
 - [Null values issue](https://osgeo-org.atlassian.net/browse/GEOS-8490)
 - [improvements](https://github.com/geosolutions-it/MapStore2/issues/2420)

*Acceptance Criteria - AC*

- TBD

**Comment by tdipisa** [comment]
closed in favour of issues in MS2 du avoid duplications
