### ISSUE TITLE
Update config.yaml with all missing layouts

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2-C040#119]
### Description
There are some missing layouts for print plugin (e.g. landscape without legend). We should align the config.yaml with latest changes applied to [mapstore2 one](https://github.com/geosolutions-it/MapStore2/tree/master/resources/geoserver/print). 

### Please indicate if this issue is related to a bug or a new feature request
- [x] Bug

*Browser Affected*
any
*Steps to reproduce*

- Open Print panel
- Select landscape

*Expected Result*

- You can print in any layout combination

*Current Result*

- You see a notification of "Not allowed layout"

**Comment by tdipisa** [comment]
Done in test environment
