### ISSUE TITLE
GetFeatureInfo panel hide the feature

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#123]
### Description
the GFI panel hide sometime the feature on the map.

### Please indicate if this issue is related to a bug or a new feature request
- [ ] Bug
- [x] New Feature

### In case of New Feature (otherwise remove this paragraph)

*Acceptance Criteria - AC*

- Find a way to recenter the map when the GFI panel is opened

connected to geosolutions-it/MapStore2#2787

**Comment by offtherailz** [comment]
A simple solution is to center the map on the point, if it is in the hide zone. 
It works for desktop version but for mobile you have something like this: 
![image](https://user-images.githubusercontent.com/1279510/34986038-6251594e-fab6-11e7-9523-0f17f775973d.png)
The best solution is to calculate the current visible viewport and move the map to center the marker over there. 

Another consideration is that you could fall in this situation.
![image](https://user-images.githubusercontent.com/1279510/34986144-c223cbea-fab6-11e7-8057-05ea75028282.png)

So you have also to calculate other panel opened. 
Fortunately we can use the layout reducer to calculate how many pixel you have occupied by the side elements. Take also into account that actually featureInfo and TOC can overlap so the map is not visible anymore and you are not able to calculate the position to move. 
In this rare case MS2 could be smart enough to close the TOC and center on the remaining area.

Of course, if the window width is smaller than FeatureInfo the app should not zoom neither fail.
