### ISSUE TITLE
Check ZONE_STORICHE visibility

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2-C040#128]
### Description (reported)
Il layer ZONE_STORICHE non compare disponibile nell’elenco del catalogo CSW sebbene sia presente invece nelle capabilities WMS. Questa problematica potrebbe coinvolgere anche altri layers. 

TODO: compile below:
### Please indicate if this issue is related to a bug or a new feature request
- [x] Bug
- [ ] New Feature

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- A list of steps to reproduce the bug
- ...

*Expected Result*

- Describe here the expected result 

*Current Result*

- Describe here the current behavior

### In case of New Feature (otherwise remove this paragraph)

*Acceptance Criteria - AC*

- Describe the list of Acceptance Criteria
- ...

**Comment by offtherailz** [comment]
La problematica è dovuta al carattere accapo nell'abstract del layer. Rimuovendolo il layer torna ad essere ricercabile. 
Attualmente è stato aggiornato sul geoserver master. Ricaricando gli slave si otterrà questo fix anche per MapStore.

**Comment by tdipisa** [comment]
il comune di genova si occuperà di far ripartire gli slave e controllare se il problema interessa altri layer. Da controllare a prossimo deploy
