### ISSUE TITLE
Check map 1000000677

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2-C040#129]
### Description
La mappa con ID 1000000677 (protezione civile ad accesso riservato) presenta delle problematiche con il tool di “Filtra usando un livello”: il tool non si abilita e si visualizza un alert rosso poco chiaro. Con le nuove mappe create il problema non si presenta. Non risulta possibile effettuare una query spaziale incrociata (cross layer) tra le aree esondabili e il livello delle scuole. Invece aprendo gli stessi livelli nel ‘visualizzatore’ generico la query spaziale funziona. Sembra non sia avvenuta correttamente la migrazione ms1 e ms2

TODO:  

### Depends On (optional)
 - 

### Please indicate if this issue is related to a bug or a new feature request
- [x] Bug
- [ ] New Feature

*Steps to reproduce*

- see description

**Comment by offtherailz** [comment]
After a small inspection I noticed that map still contains ms2-authkey parameters, as for this bug:
https://github.com/geosolutions-it/MapStore2/issues/2369 


The map has been created in Aug. 
```
creation": "2017-08-29T11:47:29.021+02:00",
```
the fix: 
https://github.com/geosolutions-it/MapStore2/commit/fd826057cea0f499d4fd2f7de3d634126f5c9878

has been applied in November. It doesn't recover the old maps. 
Updating the map content by removing ms2-authkey from the URLs solved the problem.

**Comment by offtherailz** [comment]
@tdipisa we should check the 39 maps in production to make sure remove this issue from every map.

**Comment by tdipisa** [comment]
@offtherailz you can proceed with this check as soon as possible

**Comment by tdipisa** [comment]
Il comune di genova controllerà quali altri mappe sono interessate dal problema riportato qui e in #130. Geosolutions agornerà quindi le mappe interessate al prossimo deploy
