### ISSUE TITLE
Migrate GeoCollect to Genova servers

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2-C040#135]
I dati correnti di GeoCollect dovranno essere salvati su DB del Comune di Genova su DB PostgGIS. L’applicativo andrà quindi riconfigurato ed installato nell’infrastruttura del Comune di Genova ed i dati attualmente presenti sul server GeoSolutions backuppati e ripristinati nel nuovo DB. 

- [ ] Creazione del nuovo database e migrazione dati
- [ ] Migrazione di tutti gli applicativi coinvolti (GeoServer, GeoStore, MapStore, OpenSDI-manager)

Da chiarire:
- [ ] (Android) Al login gli utenti dovranno selezionare il server di Genova invece di quello di GeoSolutions. E' necessaria una app personalizzata per Genova con il server di riferimento pre-impostato? Dovrà essere pubblicata su un account Google del Comune di Genova?
- [ ] Il sito dovrà supportare HTTPS?

**Comment by tdipisa** [comment]
closed for inactivity
