### ISSUE TITLE
Plugin di Ricerca

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#140]
Aggiunta della ‘ricerca per indirizzo’ nel plugin cantieri. Abilitare ricerca Nominatim nella mappa del plugin dei lavori pubblici.

connected to geosolutions-it/MapStore2#2798

**Comment by chiaracurcio** [comment]
Ci sarebbero le seguenti cose da aggiustare:
La barra di ricerca nel plugin 'Lavori Publici' dovrebbe essere a sinistra (come attualmente) ma con lunghezza maggiore tale da far leggere l'intero comando scritto all'interno "cerca un indirizzo o inserisci coordinate" (al momento si vede spezzato e non si capisce). 
La lente per fare la ricerca è cliccabile ma una volta scritto l'indirizzo nella barra essa scompare lasciando solo la x per fare il reset, ciò non ha molto senso.
