### ISSUE TITLE
Integrazione supporto a dati di elevazione da GeoServer

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#147]
Consentire a GeoServer di fornire i DTM di Genova. Successivamente mostrare di dati di elevazione in MapStore2  all'interno del footer, come attualmente viene fatto per il mouse position.

![elevation](https://user-images.githubusercontent.com/1280027/38489326-4dd6366c-3be6-11e8-9471-2cc268fdaf18.png)

**Comment by randomorder** [comment]
@tdipisa 
Plugin installed in the Test environment. Sample data ( /share/ELEVATION/elevation.tif ) published:

![ele](https://user-images.githubusercontent.com/5264230/38353976-5f845866-38b8-11e8-915e-8d27622a0e6b.png)

Layer name is _elevation_, published in workspace _TEST_

**Comment by mbarto** [comment]
Needs https://github.com/geosolutions-it/MapStore2/issues/2815
