### ISSUE TITLE
Privacy Note

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2-C040#156]
### Description
Fornire un link alle note sulla privacy verso l'indrizzo  
```
http://www.comune.genova.it/content/note-legali-e-privacy
```

### Please indicate if this issue is related to a bug or a new feature request
- [x] New Feature

*Acceptance Criteria - AC*

- Il link deve essere visibile sia nel footer che in mappa.

**Comment by chiaracurcio** [comment]
you can't open this link: http://www.comune.genova.it/content/note-legali-e-privacy, please correct this problem
