### ISSUE TITLE
Add GeoNetwork link in menu options and update translations

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2-C040#164]
### Description

Add a link in menu options to open GeoNetwork in a different tab.
proposal:

![2018-06-19 14_41_40-window](https://user-images.githubusercontent.com/19175505/41597874-f595a3a4-73ce-11e8-8549-6db7b958dc47.png)

Update translation:
- shapefile import 
```
Trascina qui i file o fai click per selezionare i file vettoriali da importare.(file supportati:
SHAPEFILES contenuti in archivi zip, KML/KMZ e GPX, sistemi di riferimento Epsg:3003,
Epsg:4326)
```
- legend:
```
legenda non disponibile alla scala attuale
```

**Comment by chiaracurcio** [comment]
clicking the GEONETWORK option in the burger menù the link to GeoNetwork opens in a different tab but is in english language: https://mappe.comune.genova.it/geonetwork/srv/eng/main.home
we can also link the italian version: https://mappe.comune.genova.it/geonetwork/srv/ita/main.home
Can we do that?
