### ISSUE TITLE
Different results between chrome and Firefox

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2-C040#184]
### Description
Searching for "Struppa" return different results for Chrome and Firefox. 

### Please indicate if this issue is related to a bug or a new feature request
- [x] Bug
- [ ] New Feature

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [x] Firefox
- [ ] Safari

*Browser Version Affected*
n/a

*Steps to reproduce*

- Open a map with Chrome and search for "Struppa". You will se "VIA STRUPPA" as 2nd result
- Open a map with Firefox and search for "Struppa. 

*Expected Result*

- I see the same results

*Current Result*

- I can't see the first 2 results of chrome version, but I can see 2 more results

**Comment by offtherailz** [comment]
The reason of this issue is that the results are 17, but here there is a slice to avoid to show to many results, limiting the results to 15. 
https://github.com/geosolutions-it/MapStore2/blob/22bbfe82be2db71cd622d27bed457ccd41bb1332/web/client/epics/search.js#L65

The reason is in the `sort` for array is not stable in JavaScript. So when the sort function is applied, by prioirity, the item with same priority (all, in this case) may have different position. 

We should instead: 
 - [ ] Preserve original order and place the new results coming from the extenal service in the correct place of the new array, without re-sorting anything. (This also guarantees that original order from sortBy option is preserved). 
 - [ ] Extend the max results to display (or make it configurable) is also a requirement, because when you have many results, like in this case, you may see the needed result omitted. Notice that there is a `maxFeatures: 20` configured for the WFS search service, and max 15 in total as results. We have also nominatim results, with less priority, to display.

**Comment by MV88** [comment]
requires https://github.com/geosolutions-it/MapStore2/issues/3976

**Comment by tdipisa** [comment]
We have to update the revision of MS for this and provide a PR

**Comment by tdipisa** [comment]
The problem still occurs: "Via Struppa" does not appear in the results. Probably we just need to customize **maxResults** in localConfig, right @MV88?

**Comment by MV88** [comment]
The results are the same between Firefox and Chrome.
The problem is that the maxResults flag is using the default value which is 15
Currently if you enter "Via Struppa" you get 3 results from nominatim and 12 from the custom search service (2 of them are excluded, hence "Via Struppa")

In order to fix this, it should be enough to customize this flag inside localConfig.json
- Find "Search" plugin under **desktop**
- add a maxResults: 20 or any number you like at the same level of searchOptions
