### ISSUE TITLE
GeoFence - Regole di sicurezza

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#191]
### Description
Abitanti per civico, se alcuni attributi vengono esclusi tramite Details in Geofence, non viene visualizzato all’esterno della rete comunale (SITGEO:V_CIVICI_ABITANTI). Il layer dovrebbe essere visibile dall'esterno della rete comunale con accesso anonimo, solo alcuni attributi non dovrebbero essere visibili in queste condizioni.

Le regole che si applicano al layer selezionato sono infatti le seguenti: 

![rules](https://user-images.githubusercontent.com/1280027/58460781-946a8b80-812e-11e9-98b2-b3eee3215f3e.jpg)

La terza regola, che dovrebbe essere applicata a tutti, ha questo filtro sugli attributi:

![rules2](https://user-images.githubusercontent.com/1280027/58461095-2d99a200-812f-11e9-899a-8746ac7f302f.jpg)

Effettuando la DescribeFeatureType da navigazione in incognito ed essendo disconnessi dalla VPN ed all’esterno della rete del comune si ha questo risultato:

```
{name: "INDIRIZZO", maxOccurs: 1, minOccurs: 0, nillable: true, type: "xsd:string",…}
{name: "N_ABITANTI", maxOccurs: 1, minOccurs: 0, nillable: true, type: "xsd:number",…}
{name: "N_FAMIGLIE", maxOccurs: 1, minOccurs: 0, nillable: true, type: "xsd:number",…}
{name: "COD_STRADA", maxOccurs: 1, minOccurs: 0, nillable: true, type: "xsd:string",…}
{name: "CODICE_CONTROLLO", maxOccurs: 1, minOccurs: 0, nillable: true, type: "xsd:string",…}
{name: "ID", maxOccurs: 1, minOccurs: 1, nillable: false, type: "xsd:number", localType: "number"}
{name: "GEOMETRY", maxOccurs: 1, minOccurs: 0, nillable: true, type: "gml:Geometry",…}
{name: "PERICOLOS_IDRO", maxOccurs: 1, minOccurs: 0, nillable: true, type: "xsd:string",…}
{name: "RISCHIO_IDRO", maxOccurs: 1, minOccurs: 0, nillable: true, type: "xsd:string",…}
{name: "PERICOLOS_INC", maxOccurs: 1, minOccurs: 0, nillable: true, type: "xsd:string",…}
{name: "RISCHIO_INC", maxOccurs: 1, minOccurs: 0, nillable: true, type: "xsd:string",…}
{name: "PERICOLOS_FRANE", maxOccurs: 1, minOccurs: 0, nillable: true, type: "xsd:string",…}
{name: "RISCHIO_FRANE", maxOccurs: 1, minOccurs: 0, nillable: true, type: "xsd:string",…}
```

Come si vede gli attributi impostati a NONE compaiono comunque ed il layer WMS non risulta visibile.
Il client riporta che questo comportamento anomalo sembra essere presente in tutti i casi che hanno restrizioni sugli attributi impostate.

Sembra essere un bug di GeoFence. Tuttavia ho il dubbio che le regole con IP modifichino leggermente il comportamento.

Prod doc [here](https://docs.google.com/document/d/12BJy50ECXIuGktnouuoP_MvqpN5-GvGZkVIOuazGvc4/edit)

**Comment by tdipisa** [comment]
@etj please check also teh layer mediatore:v_tavole_ctc that, as reported by the client, should have some attributes set to NONE for external access: the WMS layer is visible but not the attributes.

**Comment by etj** [comment]
Da fuori VPN, utente non autenticato, gli attributi sembrano filtrati correttamente:

![image](https://user-images.githubusercontent.com/717359/58466699-799e1400-813a-11e9-9916-63159b4a96e7.png)

**Comment by etj** [comment]
GetFeatureInfo funzionante:

https://mappe.comune.genova.it/geoserver/wms?service=WMS&version=1.1.1&request=GetFeatureInfo&exceptions=application/json&id=SITGEO:V_CIVICI_ABITANTI__6&layers=SITGEO:V_CIVICI_ABITANTI&query_layers=SITGEO:V_CIVICI_ABITANTI&x=51&y=51&height=101&width=101&srs=EPSG:3857&bbox=990376.6099744015,5529017.4637101265,990497.237159664,5529138.090895389&feature_count=10&info_format=text/xml&ENV=locale:en

Response:
```
<?xml version="1.0" encoding="UTF-8"?>
<wfs:FeatureCollection xmlns="http://www.opengis.net/wfs" xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:SITGEO="http://sit.comune.genova.it/SITGEO" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://sit.comune.genova.it/SITGEO https://mappe.comune.genova.it:443/geoserver/wfs?service=WFS&amp;version=1.0.0&amp;request=DescribeFeatureType&amp;typeName=SITGEO%3AV_CIVICI_ABITANTI http://www.opengis.net/wfs https://mappe.comune.genova.it:443/geoserver/schemas/wfs/1.0.0/WFS-basic.xsd">
  <gml:boundedBy>
    <gml:null>unknown</gml:null>
  </gml:boundedBy>
  <gml:featureMember>
    <SITGEO:V_CIVICI_ABITANTI fid="V_CIVICI_ABITANTI.fid-558a5511_16afdcbf30e_-7088">
      <SITGEO:ID>89680</SITGEO:ID>
      <SITGEO:INDIRIZZO>VIA LUIGI DOTTESIO 16</SITGEO:INDIRIZZO>
      <SITGEO:N_ABITANTI>17</SITGEO:N_ABITANTI>
      <SITGEO:GEOMETRY>
        <gml:Point srsName="http://www.opengis.net/gml/srs/epsg.xml#3857">
          <gml:coordinates xmlns:gml="http://www.opengis.net/gml" decimal="." cs="," ts=" ">990428.95407712,5529085.93880629</gml:coordinates>
        </gml:Point>
      </SITGEO:GEOMETRY>
      <SITGEO:N_FAMIGLIE>5</SITGEO:N_FAMIGLIE>
    </SITGEO:V_CIVICI_ABITANTI>
  </gml:featureMember>
</wfs:FeatureCollection>
```

**Comment by etj** [comment]
GetMap *non* funzionante dall'esterno:

https://mappe.comune.genova.it/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=SITGEO%3AV_CIVICI_ABITANTI&STYLES=&SRS=EPSG%3A3857&CRS=EPSG%3A3857&TILED=true&WIDTH=256&HEIGHT=256&BBOX=989706.6422364637%2C5528843.12992337%2C990012.3903496044%2C5529148.87803651

Response dall'esterno:

**Comment by etj** [comment]
Lo stile di default ABITANTI_X_CIVICO contiene il seguente snippet:
```
<ogc:Div>
         <ogc:PropertyName>N_FAMIGLIE</ogc:PropertyName>
         <ogc:PropertyName>2</ogc:PropertyName>
</ogc:Div>
```
dove `2` non è un nome di attributo valido.

**Comment by etj** [comment]
Test gella GetFeatureInfo su TAVOLE_CTC:

```
curl 'https://mappe.comune.genova.it/geoserver/wms?service=WMS&version=1.1.1&request=GetFeatureInfo&exceptions=application%2Fjson&id=MEDIATORE:V_TAVOLE_CTC__7&layers=MEDIATORE:V_TAVOLE_CTC&query_layers=MEDIATORE:V_TAVOLE_CTC&x=51&y=51&height=101&width=101&srs=EPSG:3857&bbox=991266.384756784,5528525.400340546,991387.0119420465,5528646.027525809&feature_count=10&info_format=text%2Fhtml&ENV=locale:en'

{"version":"1.1.1","exceptions":[{"code":"noApplicableCode","locator":"noLocator","text":"java.io.IOException: Error occured processing content template content.ftl for MEDIATORE:V_TAVOLE_CTC\nError occured processing content template content.ftl for MEDIATORE:V_TAVOLE_CTC\nExpression feature.LINK_DGN is undefined on line 58, column 68 in content.ftl."}]}
```

**Comment by tdipisa** [comment]
@etj If I'm outside the VPN but logged as admin in MS the error does not appears, this probably due to a different mathcing GF rule

**Comment by tdipisa** [comment]
The client will apply the reported fixes via ML to get back to us with further checks if needed.
