### ISSUE TITLE
Codici IPA non aggiornati da vista XML

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#197]
### Description
E' stato riscontrato un problema nella modifica del codice IPA all'interno della vista XML del metadato. alcuni metadati del comune hanno un IPA temporaneo che deve essere sostituito con quello corretto.

Step to reproduce:

- Aprire un metadato 
- Abilitare la vista XML 
- Modificare i codici IPA presenti (si deve usare iil codice corretto 'c_d969:')
- Salvare il metadato

Expected result:

- Il metadato viene salvato correttamente con i codici IPA corretti

Current result:

- Il metadato viene salvato ma i codici IPA rimangono inalterati

**Comment by etj** [comment]
L'editor RNDT non permette la modifica del codice IPA primario, in quando potrebbe rompere le relazioi di parentela con i dataset di gerarchia superiore.

Ho apportato delle modifiche in modo da rendere possibile questo editing, confidando che vengano utilizzate per una correzione globale dei codici IPA all'interno di un catalogo.

Da testare.
