### ISSUE TITLE
logout from new map removes some backgrounds that are not restored after login

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2-C040#216]
### Description
back ground list changes and is not restored after logout/login and a layer is added to the TOC.

while checking this align the list of background with production
note that google satellite does not render correctly (with watermark).

### Please indicate if this issue is related to a bug or a new feature request
- [x] Bug
- [ ] New Feature

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- login as admin
- create a new map
- take not of toc layers (empty) and backgrounds list
- logout
- check expect #1
- login as admin
- check expect #2

*Expected Result*

1) the toc is still empty and the background that are visible only for admin to be hidden

2) the toc is empty and the background list is updated as the first time the user enter the new map
*Current Result*
1)
![image](https://user-images.githubusercontent.com/11991428/60955071-661cc600-a300-11e9-92d7-cd2842ab0fec.png)

- the toc has a layer 
- the list of background is shortened (check if it is correct)

2)
- the bakground list is not restored
- the toc continues to have the e geos layer

### Other useful information (optional):
the same happen on production

**Comment by tdipisa** [comment]
see:
see https://github.com/geosolutions-it/MapStore2/issues/3935
