### ISSUE TITLE
Get feature info results layout has some problems

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2-C040#217]
### Description
there is a horizontal scrollbar that now is visible for the [geocollect map](http://vm-linuxgeofetest.comune.genova.it/MapStore2/#/viewer/openlayers/geocollect)

- try to check to find a result that have immagini tab near segnalazioni like
![image](https://user-images.githubusercontent.com/11991428/60958782-3b823b80-a307-11e9-86c0-b1b4af24eddb.png)

the vertical scroll bar then is the same for all layers even if some layers has less results
![image](https://user-images.githubusercontent.com/11991428/60959036-bea39180-a307-11e9-9b0b-29109483e8cb.png)

### Please indicate if this issue is related to a bug or a new feature request
- [x] Bug
- [ ] New Feature

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

1)
- open the geocollect map 
- perform a get feature info at this location Lat: 44,457 - Long: 8,714

2)
- click on 44,419 - Long: 8,941
- switch to segnalazione muri
- scroll down is not coherent with the content

*Expected Result*

1) to not see the scroll bar (if possible)

2) the scroll bar should adapt to each layer results

*Current Result*
 
1) if you scroll down a 
for the immagini tab see this 
![image](https://user-images.githubusercontent.com/11991428/60957772-8307c800-a305-11e9-8231-b5d1e1892ef6.png)

2) the scroll bar is not coherent and you can scroll down a lot even if there is no result for that layer

### Other useful information (optional):
this is no happening in production the horizontal scroll bar.
the other problem with vertical scrollbar instead is present

**Comment by tdipisa** [comment]
closed for inactivity
