### ISSUE TITLE
Finalize migration to latest mapstore2

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2-C040#235]
### Description
I noticed some issues 
 - [ ] index.html should be aligned with indexTemplate.html (check also other files)
 - [ ] a clear build (without node_modules folder) produced some issues on my machine, please verify.
    - error with acorn dependencies
    - issues of multiple react instances
- [ ] Please align libs from mapstore

**Comment by MV88** [comment]
the issue related to the clear build is more complex than expected.
i would crate a new issue for it in order to proceed with the other points and continue investigation aside those.
@tdipisa agree?
