### ISSUE TITLE
Ricerca layers in tool di catalogo

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#238]
### Description
Filtro nella ricerca catalogo: possibilità di inviare richiesta di ricerca dopo qualche secondo dalla digitazione senza dover premere sul pulsante 

### Other useful information (optional):
Il catalogo è uno dei primi tool sviluppati quindi è strutturato come le prime versioni di mapstore. Queste erano molto legate all’interfaccia e basati su i thunk. Al fine di consentire questa funzionalità è necessario un piccolo refactor per passare ad utilizzare observable, in modo da poter gestire il flusso asincrono di testo e risposte dalla API in modo ottimale.

**Comment by MV88** [comment]
requires https://github.com/geosolutions-it/MapStore2/issues/3985

**Comment by tdipisa** [comment]
PR in pending review MS side, waiting for merge, then update the MS revision and do a PR
