### ISSUE TITLE
Query Filtro per livello

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#239]
### Description
MS2  in alcune mappe dove i livelli sono precaricati, si puo' effettuare la query multilivello e in altre no

### Other useful information (optional):
Provare [questa mappa](https://mappe.comune.genova.it/MapStore2/#/viewer/openlayers/1000000604) abilitando e facendo la query sul layer scuole.
I layer della mappa hanno search.url = “/geoserver/wfs?” oppure “/geoserver/wfs?&” e non fanno match per via di [questa funzione](https://github.com/geosolutions-it/MapStore2/blob/ca2e60fb3a394a4aa3cc8fa9ed33b10616808b24/web/client/components/data/query/CrossLayerFilter.jsx#L23). Perché [isSameUrl](https://github.com/geosolutions-it/MapStore2/blob/ca2e60fb3a394a4aa3cc8fa9ed33b10616808b24/web/client/utils/URLUtils.js#L35) non considera questa.

Bisognerebbe investigare anche sul perché gli url wfs si sono sporcati

**Comment by MV88** [comment]
These are url of the layers in the indicated map
```
[
    {
        "name": "SITGEO:V_BACINI_IDROGRAFICI",
        "url": "/geoserver/wfs?&"
    },
    {
        "name": "SITGEO:V_CLASSI_SISMICHE",
        "url": "/geoserver/wfs?"
    },
    {
        "name": "SITGEO:V_FRANE_VINC",
        "url": "/geoserver/wfs?"
    },
    {
        "name": "SITGEO:V_PIANO_BACINO",
        "url": "/geoserver/wfs?"
    },
    {
        "name": "SITGEO:V_INCENDI_INTERFACCIA",
        "url": "/geoserver/wfs?"
    },
    {
        "name": "PROTCIV:V_PC_AREE_EMERGENZA",
        "url": "/geoserver/wfs?"
    },
    {
        "name": "SITGEO:SCUOLE_AGG_GEO",
        "url": "/geoserver/wfs"
    }
]
```
Since they are not the same in the Advanced search of layer Scuole it appears only one layers which is Scuole because is the only one with "/geoserver/wfs" as url

We need to ignore cases where the path is dirty

**Comment by MV88** [comment]
requires https://github.com/geosolutions-it/MapStore2/issues/2749
