### ISSUE TITLE
Filtro in stampa livello

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#240]
### Description
Se filtro nella tabella attributi e vado in stampa questa non applichera' il filtro

### Other useful information (optional):
Risolvendo la issue #3509 prevista per la milestone 2019.02.00, il filtro sarà disponibile anche al di fuori del contesto FG, il semplice passaggio del filtro come parametro di stampa all'interno del contesto FG richiede un effort minore.

**Comment by MV88** [comment]
The print tool will use:
 - the global filter added to the layer (if present)
 - the one added to the Feature Grid (if present)

**Comment by MV88** [comment]
requires https://github.com/geosolutions-it/MapStore2/issues/4005
