### ISSUE TITLE
Layers list query param

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#241]
### Description
Possibilità di aggiungere layers ulteriori alla mappa con 'layers' e 'source URL', per Genova possiamo assumere che i layers vengano dal loro catalogo. Si richiede in pratica che ci sia nella URL anche l'elenco livelli per richiamare un visualizzatore e aggiungere i livelli al volo.

### Other useful information (optional):
Sarebbe utile per il cliente avere una opzione per introdurre la lista layers in URL di condivisione mappa.

**Comment by MV88** [comment]
dropping here a piace of future documentation for map-query-parameters file:
````
#### Add Layers (not implemented yet)

This action allows to add layers from catalog present in the map

Requirements:
- the number of values must be even
- catalog name must be present in the map


Example:
```
{
    "type": "CATALOG:ADD_LAYERS_FROM_MAP_URL",
    "layers": ["layer1", "catalog1", "layer2", "catalog2"]
}
?actions=[{"type":"CATALOG:ADD_LAYERS_FROM_MAP_URL","layers":["layer1","catalog1","layer2","catalog2"]}]
```
````

**Comment by MV88** [comment]
requires https://github.com/geosolutions-it/MapStore2/issues/4009
