### ISSUE TITLE
GeoServer Error for some aerial mosaics

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#263]
### Description
Nella cartella \\vm-linuxgeofe\disco_dati\GEOSERVER_DATA_DIR_TEST\data\foto le 2 foto aeree da mosaicare in Geoserver. A noi da il seguente errore

Failed to create reader from file:data/foto and hints Hints: FORCE_LONGITUDE_FIRST_AXIS_ORDER = true GRID_COVERAGE_FACTORY = GridCoverageFactory TILE_ENCODING = null REPOSITORY = org.geoserver.catalog.CatalogRepository@82b3f72 FORCE_AXIS_ORDER_HONORING = http COMPARISON_TOLERANCE = 1.0E-8 FILTER_FACTORY = FilterFactoryImpl STYLE_FACTORY = StyleFactoryImpl EXECUTOR_SERVICE = java.util.concurrent.ThreadPoolExecutor@1aebe0be[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0] LENIENT_DATUM_SHIFT = true FEATURE_FACTORY = org.geotools.feature.LenientFeatureFactoryImpl@634d30cb

**Comment by Gnafu** [comment]
Tomcat non aveva i permessi in scrittura sulla cartella.
Dopo aver eseguito un "chmod o+w" sulla cartella GeoServer ha potuto scrivere i metadati del mosaico dentro la cartella, creando correttamente lo store.
Ho pubblicato un later "TEST:ortofoto" a partire da quelle due immagini.

Alcuni consigli:
- Non tenere quelle immagini dentro la datadir; spostarli in una cartella esterna e creare nella datadir una cartella con la sola configurazione del mosaico (che punterà alla cartella con le immagini): https://docs.geoserver.org/latest/en/user/data/raster/imagemosaic/configuration.html#index-and-configuration-file-creation
  - Questo per semplificare i backup della configurazione di GeoServer
- Ottimizzare le geotiff per velocizzarne la lettura da parte di GeoServer

**Comment by tdipisa** [comment]
wait the client confirmation before closing
