### ISSUE TITLE
Users that log-in with Spid are not selectable via geofence

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2-C040#27]
Seem to not be present on database. [test environment, maybe MapStore1].

**Comment by Gnafu** [comment]
SIRAC gateway is not currently accessible.

**Comment by offtherailz** [comment]
The issue was due to a wrong configuration of test environment (didn't update the admin password). 

This fix have to be ported in test, together with the changes to the web.xml file changes.
