### ISSUE TITLE
Cannot categorize after MapStore2 and GeoServer upgrade

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2-C040#284]
### Description
The categorization tool in mapstore is not showing anything on the map

### Please indicate if this issue is related to a bug or a new feature request
- [x] Bug
- [ ] New Feature

### In case of Bug (otherwise remove this paragraph)
Chrome affected

*Steps to reproduce*

- Open the categorization tool
- categorize
- PLEASE FILL THIS LIST

*Expected Result*

- Something on the map

*Current Result*

- Nothing showed on the map

### Other useful information (optional):

Offending request:
https://mappe.comune.genova.it/geoserver/wms?SERVICE=WMS&VERSION=1.1.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&LAYERS=SITGEO:P_VIEW_SEAP_GAS&STYLES=&SRS=EPSG:3857&CRS=EPSG:3857&TILED=true&ms2-authkey=0a80488f-58b8-4f79-874e-4e47edd2dfce&SLD=https%3A%2F%2Fmappe.comune.genova.it%3A443%2Fgeoserver%2Frest%2Fsldservice%2FSITGEO%3AP_VIEW_SEAP_GAS%2Fclassify.xml%3Fattribute%3DCO2%26intervals%3D8%26method%3Dquantile%26ramp%3Dcustom%26colors%3D%2523000000%252C%2523240000%252C%2523490000%252C%25236d0000%252C%2523920000%252C%2523b60000%252C%2523db0000%252C%2523ff0000%26open%3Dfalse%26strokeWeight%3D-1%26strokeColor%3D%2523ff0000%26viewparams%3DANNO%253A2016%26customClasses%3D1.1011%252C22.518%252C%2523000000%253B22.518%252C48.445%252C%2523240000%253B48.445%252C81.193%252C%2523490000%253B81.193%252C118.905%252C%25236D0000%253B118.905%252C168.246%252C%2523920000%253B168.246%252C232.83%252C%2523B60000%253B232.83%252C338.04%252C%2523DB0000%253B338.04%252C16597.660000000003%252C%2523FF0000%26fullSLD%3Dtrue%26ms2-authkey%3D0a80488f-58b8-4f79-874e-4e47edd2dfce&viewparams=ANNO:2016&WIDTH=256&HEIGHT=256&BBOX=975947.9771451317,5535263.840299323,978393.9620502574,5537709.825204449

Geoserver is used twice in this request, first the SLD service, then the WMS.
Log files are attached.

[https://app.zenhub.com/files/81931957/10963341-5777-4576-b74e-beb39573890d/download](https://app.zenhub.com/files/81931957/10963341-5777-4576-b74e-beb39573890d/download)

[https://app.zenhub.com/files/81931957/61747361-e2c5-4725-b6af-0f684e9ef5f0/download](https://app.zenhub.com/files/81931957/61747361-e2c5-4725-b6af-0f684e9ef5f0/download)

**Comment by tdipisa** [comment]
Here the test that fails:
https://studio.cucumber.io/projects/47740/test-runs/375738/folder-snapshots/3587701/scenario-snapshots/13316163/test-snapshots/17239771

**Comment by Gnafu** [comment]
JIRA: https://osgeo-org.atlassian.net/browse/GEOS-9539
Tested on DEV
Waiting for client feedback before production deploy

**Comment by tdipisa** [comment]
The fix works fine also in PROD but for this layer:
INCENDI_INTERFACCIA

MS reports an error:
![image](https://user-images.githubusercontent.com/1280027/76759675-76891880-678c-11ea-964d-45c06330b73f.png)

because the Geometry type is set to generic GS side:
https://mappe.comune.genova.it/geoserver/wfs?service=wfs&version=2.0.0&request=DescribeFeatureType&typeNames=SITGEO:V_INCENDI_INTERFACCIA

The layer setting in GS must be fixed.
