### ISSUE TITLE
Deformed background preview thumbnails

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#292]
### Description
Look at this map:

https://mappe.comune.genova.it/MapStore2/#/viewer/openlayers/1000000604

The preview of the background layer 'BASE_CARTOGRAFICA' looks deformed:

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/92db6544-f9ba-49da-a2e2-b723b092b04d)

Since a thumbnail is not specified, the background selector retrieves it from the WMS with the following request that is too big for the preview: since the image is adapted to the preview container (max 98x98 or 128x128 px), it is finally deformed.

https://mappe.comune.genova.it/geoserver/wms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&STYLES&LAYERS=BASE_CARTOGRAFICA&SRS=EPSG:3003&WIDTH=600&HEIGHT=301&BBOX=1497725.7662845084,4915082.348986519,1498441.5612306271,4915440.246459578

**Comment by offtherailz** [comment]
Is not get automatically, it is the thumbnail present in new.json.
We could replace it with something square, like this.

https://mappe.comune.genova.it/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fjpeg&TRANSPARENT=true&LAYERS=BASE_CARTOGRAFICA&STYLES=&SRS=EPSG%3A3857&CRS=EPSG%3A3857&TILED=true&ms2-authkey=a7011b1a-e3c1-48a1-9e29-6e3028f6e33d&WIDTH=128&HEIGHT=128&BBOX=984661.7983696423%2C5531441.988885064%2C984814.6724262127%2C5531594.862941634
