### ISSUE TITLE
MS Deploy in Test Environment

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#304]
### Description
Deploy of the updated downstream project (#301) in Test environment.

### Other useful information (optional):

New Categories need to be created during the deploy in GeoStore DB:

GEOSTORY
CONTEXT
TEMPLATE
USERSESSION

**Comment by tdipisa** [comment]
We are waiting the WAR file from @MV88 for this deploy.

**Comment by MV88** [comment]
[Here](http://demo.geo-solutions.it/share/comunege/) is the new **war**

**Comment by tdipisa** [comment]
@randomorder we are ready .
The client need to be notified via email before starting the deploy process.

**Comment by randomorder** [comment]
@giacomoc92 please move on with the deploy before the end of the day

**Comment by MV88** [comment]
i've update the war in the same folder [Here](http://demo.geo-solutions.it/share/comunege/)
