### ISSUE TITLE
MS Deploy in Production Environment

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#305]
### Description
Deploy of the updated downstream project (#301, #305) in Production environment.

**Comment by tdipisa** [comment]
@MV88 we have to deploy in production the updated MS currently in test. Therefore, we need a WAR file for the deploy on Monday 13 July. This means:

- @offtherailz we have to review and merge [this](https://github.com/geosolutions-it/MapStore2-C040/pull/320) PR first
- @MV88 we have to tag the master branch (I think v1.3-test is better) 
- @MV88 we have to do a PR to update the production branch and based on this the WAR file to deploy (put please a comment here in the issue with the link to download it)
- As soon as we deploy and test, we can merge the PR and do a Tag also for the release in production (v1.3)

@randomorder the WAR should be available tomorrow.

**Comment by MV88** [comment]
@randomorder i cannot put here the WAR files for test and production because they contain sensible information,
so i've sent you the link to fetch them via skype

**Comment by tdipisa** [comment]
@randomorder remember that with this new version the DB schema is changed a bit. During the test deploy @giacomoc92 run the [migration scripts](https://mapstore.readthedocs.io/en/v2020.02.00/developer-guide/mapstore-migration-guide/#migration-from-20200100-to-20200200).

**Comment by randomorder** [comment]
MS updated in PROD
