### ISSUE TITLE
Map Templates, Annotations, Docs, About, Reset User Section plugins are not visible on context

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2-C040#313]
## Description

When Map Templates, Annotations, Docs, About, Reset User Section plugins are enabled, they are present in the context

## How to reproduce

- click on Context Manager
- Click on New context
- On the third step enable the plugins
- Click on Save
- Open the context
- click on Burger Menu

*Expected Result*

when these plugins are enabled, they are present in the context

*Current Result*

These plugins are not visible in the context

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
I suggest to not include usersession plugin that can be missleading, do you agreee @tdipisa ?

The other wasn't working because they was not included in plugins.js of this project.

Going to include the others
