### ISSUE TITLE
Enable selection of current plugin for user tool does not work

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2-C040#314]
## How to reproduce

- click on Context Manager
- Click on New context
- On the third step enable the catalog plugin
- click on Enable selection of current plugin for user
- Click on Save
- Open the context
- click on Burger Menu

*Expected Result*

The catalog plugin is present on the User Extension button

*Current Result*

The  User Extension button is not present on context

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
This is for the same problem explained in this comment: 
https://github.com/geosolutions-it/MapStore2-C040/issues/313#issuecomment-650258439

UserExtensions plugin was missing,going to align plugins included
