### ISSUE TITLE
CRS selector plugin in not visible on context

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2-C040#315]
## Description

By adding only the CRS selection plug-in, this plugin is not visible

## How to reproduce

- click on Context Manager
- Click on New context
- On the third step enable the CRS slector plugin
- Click on Save
- Open the context
- click on Burger Menu

*Expected Result*

 The CRS selector is visible on context

*Current Result*

 The CRS selector is not visible on context

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
Same of https://github.com/geosolutions-it/MapStore2-C040/issues/313#issuecomment-650258439
