### ISSUE TITLE
Green popup message does not appear after saving a context

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2-C040#316]
## Description

En example of green message that should appear:
![image](https://user-images.githubusercontent.com/1280027/77449405-2e07d580-6df2-11ea-8beb-ff1f4590d409.png)

## How to reproduce

-  Click  on New context
- Add Title
- Click Next
- Click save

*Expected Result*

The green message appears after saving the context

*Current Result*

The green message popuo does not appear after saving the context

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
Need to investigate and test locally.
