### ISSUE TITLE
Some plugins are disabled in test

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#319]
### Description
- Identify: only the **More info** tool is availabel in toolbar. Please enable the other currently missing.

![image](https://user-images.githubusercontent.com/1280027/86812553-6e2c5480-c07f-11ea-9b83-ca565a8067ed.png)

- Measurement: the button to convert a measurement to annotation is not present (**probably related to the next point**)

![image](https://user-images.githubusercontent.com/1280027/86812629-813f2480-c07f-11ea-8801-3621dc32cfcd.png)

- The annotation tool need to be enabled

**Comment by MV88** [comment]
@tdipisa do you want to enable highlight button and coordinate editor also for embedded or only for desktop?

**Comment by tdipisa** [comment]
@MV88 the same configuration tha we have in MS
