### ISSUE TITLE
Statistical Query Engine issue for a Raster Layer

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2-C040#323]
### Description
Statistics query engine should not be available for raster layers

**How to reproduce**
 - Open a new map
 - Open a Elevation layer from the Catalog
- Select the layer from TOC 
- Open the Settings and switch to Style tab

*Current Result*
The Classifica buttons is present on the style toolbar

**Comment by offtherailz** [comment]
2 issues:
- [ ] elevation layer is not working anymore on the test geoserver (TEST:elevation). Used TEST:elevation_50_cm_3003 for testing. The error was:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE ServiceExceptionReport SYSTEM "http://localhost:8081/geoserver-test/schemas/wms/1.1.1/WMS_exception_1_1_1.dtd"> <ServiceExceptionReport version="1.1.1" >   <ServiceException>
      java.lang.IllegalArgumentException: The specified coverageName elevationis not supported
The specified coverageName elevationis not supported
</ServiceException></ServiceExceptionReport>
```
- [ ] Bug in `mousePosition` selector (hard coded in map plugin, should use a shared selector instead).
This changes solve the problem:
```diff
diff --git a/web/client/plugins/Map.jsx b/web/client/plugins/Map.jsx
index c8668f55..0419d408 100644
--- a/web/client/plugins/Map.jsx
+++ b/web/client/plugins/Map.jsx
@@ -412,7 +412,7 @@ class MapPlugin extends React.Component {
     };
 }
 
-const {mapSelector, projectionDefsSelector} = require('../selectors/map');
+const { mapSelector, projectionDefsSelector, isMouseMoveCoordinatesActiveSelector} = require('../selectors/map');
 const { mapTypeSelector, isOpenlayers } = require('../selectors/maptype');
 const {layerSelectorWithMarkers} = require('../selectors/layers');
 const {highlighedFeatures} = require('../selectors/highlight');
@@ -432,7 +432,7 @@ const selector = createSelector(
         highlighedFeatures,
         (state) => state.mapInitialConfig && state.mapInitialConfig.loadingError && state.mapInitialConfig.loadingError.data,
         securityTokenSelector,
-        (state) => state.mousePosition && state.mousePosition.enabled,
+        isMouseMoveCoordinatesActiveSelector,
         isOpenlayers,
         isLocalizedLayerStylesEnabledSelector,
         localizedLayerStylesNameSelector,
```
Need to write a unit test for it to solve the issue

**Comment by offtherailz** [comment]
This is present also in current production
![image](https://user-images.githubusercontent.com/1279510/87408877-6a8b5700-c5c4-11ea-9593-288149cfdabb.png)

Open this issue for it
https://github.com/geosolutions-it/MapStore2/issues/5641

**Comment by tdipisa** [comment]
@offtherailz we have deployed in production yesterday, this issue has been identified in production but I assume it is present also in tes
