### ISSUE TITLE
MS Update to 2021.01.xx

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#330]
### Description
We have to consider (check/test) that the Thematic tool must continue to work as it is along with recent updates we provided for the visual style editor.

Involved MS developments for this project update are mainly related to the following issues, requested by c040:

- [x] https://github.com/geosolutions-it/MapStore2/issues/5930
- [x] https://github.com/geosolutions-it/MapStore2/issues/6101
- [x] https://github.com/geosolutions-it/MapStore2/issues/5883: the Query panel should reports the same measure of the measurement tool. To check the geodetic property setting, now it is set to false: both should be the same to true
- [x] https://github.com/geosolutions-it/MapStore2/issues/6102
- [x] https://github.com/geosolutions-it/MapStore2/issues/2691
- [x] https://github.com/geosolutions-it/MapStore2/issues/4150
- [x] https://github.com/geosolutions-it/MapStore2/issues/6103
- [x] https://github.com/geosolutions-it/MapStore2/issues/6338
- [x] https://github.com/geosolutions-it/MapStore2/issues/6358
- [x] https://github.com/geosolutions-it/MapStore2/issues/6316

Also some other dependencies versions must be updated according to the new MS version used: see as a reference https://github.com/geosolutions-it/MapStore2/issues/6316

### Other useful information (optional):
To evaluate the update using the stable branch 2021.01.xx of MapStore.

**Comment by allyoucanmap** [comment]
These are the components realated to the improvement of StyleEditor that could affect the Theme Classification plugin:

- [SLDService api](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/api/SLDService.js) (in partucular color ramps)

- [ThemaClassesEditor](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/style/ThemaClassesEditor.jsx)

We should test the Theme Classification plugin in an existing map and ensure the behaviour is the same as before (sldservice requests, viewparams configuration ,..) while the StyleEditor should provide the new visual ui.

These are the PRs of the improvement of the Visual Style Editor:

https://github.com/geosolutions-it/MapStore2/commit/e15c98dd6d8f39836d7740236a7f717dd67250fb#diff-854a038d3c5c80a25237ba1b7a0acb4b06c1d3da5b81faacd5f906a28ea79ced

https://github.com/geosolutions-it/MapStore2/commit/6aa6a434bdc7802a426952c29c9b9d252d73b572#diff-854a038d3c5c80a25237ba1b7a0acb4b06c1d3da5b81faacd5f906a28ea79ced

https://github.com/geosolutions-it/MapStore2/commit/c308ead2fca0782303f1faf8ad77e047785d244f#diff-854a038d3c5c80a25237ba1b7a0acb4b06c1d3da5b81faacd5f906a28ea79ced
