### ISSUE TITLE
Environment tuning for Comune di Genova

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#331]
### Description
Preliminary check of the production environment in order to evaluate the main intervention areas if any. Since during the tuning carried out in view of the elections the main bottleneck was related to the DB performances, we have to also check the status with the new Oracle version (v19).

### Other useful information (optional):
Migration to Oracle v19 done. Requests:
- Compatibility checks if needed
- Performances checks and tuning for further evaluations

We have max 1 day for a first check of the current infrastructure status: the **Genova Smart Week** event is scheduled for end of November (from 23 to 28 Nov), therefore more accesses to the infrastructure are expected in that period.

**Comment by tdipisa** [comment]
Still waiting for client feedback to know which maps we should consider to evaluate performances.

**Comment by tdipisa** [comment]
The client replied:

_come da voi richiesto vi inviamo un breve elenco di livelli e mappe su cui effettuare alcuni test per un eventuale tuning dell'infrastruttura dati spaziale:_
 
_a) livello BASE_CARTOGRAFICA:_ 

_nella mappa_ 

_Limiti Amministrativi n. accessi 130486
https://mappe.comune.genova.it/MapStore2/#/viewer/openlayers/1000001301_

_e_ 

_Visualizzatore n. accessi 68475
https://mappe.comune.genova.it/MapStore2/#/viewer/openlayers/34_

_b) livello SITGEO:V_PUC210_AREA_PUC_DEC, livello del P.U.C. del Comune di Genova
nella mappa_ 

_Livello 3 del PUC n. accessi 48138
https://mappe.comune.genova.it/MapStore2/#/viewer/openlayers/1000000900_
 
_Ci siamo basati sul numero accessi sia nelle mappe che nei livelli 
http://vm-linuxgeologt.comune.genova.it/app/kibana#/discover?_g=()
ma vorremo che fossero presi in esame anche i connettore geoserver al database, come eventualmente leggere correttamente i log GS legati al caricamento livelli (viste e tabelle) e se sono sufficienti le caratteristiche del cluster e delle macchine virtuali che lo compongono, in quanto i numeri relativi agli accessi utenza sono in forte crescita._

**Comment by tdipisa** [comment]
Last report from the client that need to be considered during this activity.

_Relativamente all'attività di tuning, volevo segnalarvi come annotazione, che stamattina
abbiamo notato un consumo elevato di memoria sul server vm-linuxgeobe1. (970 su 980 mb disponibili) e un rallentamento consistente nei geoservizi sulle mappe.
Verso le 15.00 il sistema e' crollato e ha restituito un errore 500. Tanto che alla fine abbiamo chiesto il riavvio ai nostri sistemisti.
Forse puo' essere utile controllare il log di GS del 11/11/20 tra le 9.00 e le 12.00 e cmq prima delle 15.20 momento in cui i nostri sistemisti hanno riavviato questo istanza del cluser._

**Comment by simboss** [comment]
@tdipisa this issue should stay inside support, not here.
