### ISSUE TITLE
General Review of existing GeoServer Cluster

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2-C040#338]
- [x] Resource Limits
- [x] Control Flow
- [x] Connection Pool
- [x] Tile Caching (metatile size, formats, 
- [ ] HTTP Headers Caching
- [ ] Proxy Caching (Apache HTTP? Varnish?)
- [x] Java opts and available resources

**Comment by randomorder** [comment]
Controlflow settings
``
`timeout=15
ows.global=40
user=6
ows.wms.getmap=16
ows.wms.GetFeatureInfo=8
```

WPS Security could be set more granularly and only allow processes that we actually need. I'll need feedback from @tdipisa for this. We should probably document it somewhere in MapStore

**Comment by randomorder** [comment]
Heap size is a bit on the small side with 1 GB max
