### ISSUE TITLE
Incident on vm-linuxgeobe1

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2-C040#340]
From the client on 11/11 4 pm:

> relativamente all'attività di tuning, volevo segnalarvi come annotazione, che stamattina
> abbiamo notato un consumo elevato di memoria sul server vm-linuxgeobe1. (970 su 980 mb disponibili) e un rallentamento consistente nei geoservizi sulle mappe.
> Verso le 15.00 il sistema e' crollato e ha restituito un errore 500. Tanto che alla fine abbiamo chiesto il riavvio ai nostri sistemisti.
> Forse puo' essere utile controllare il log di GS del 11/11/20 tra le 9.00 e le 12.00 e cmq prima delle 15.20 momento in cui i nostri sistemisti hanno riavviato questo istanza del cluser.

I think it is worth starting our investigation from here.

**Comment by randomorder** [comment]
I couldn't find any indication of a geoserver crash only some AJP timeout errs in the proxy for which I'll open an issue
