### ISSUE TITLE
Review CTC:RASTER_CTC configuration

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2-C040#349]
The CTC:RASTER_CTC layer does not respond properly to tile cache requests.
We get these response headers:

> geowebcache-cache-result: MISS

Please, double check GWC configuration for this layer.

**Comment by randomorder** [comment]
Thanks @ElenaGallo 

Looks ok now
![image](https://user-images.githubusercontent.com/5264230/99819160-657c7c80-2b4f-11eb-8cc0-34e977d487d3.png)
