### ISSUE TITLE
Review SITGEO:V_PONTE_MORANDI_EMERG configuration

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2-C040#354]
The SITGEO:V_PONTE_MORANDI_EMERG layer does not respond properly to tile cache requests.
We get these response headers:

> geowebcache-cache-result: MISS

Please, double check GWC configuration for this layer.

**Comment by randomorder** [comment]
Hi @ElenaGallo

geowebcache-cache-result: MISS

is fine, doesn't mean the cache is not working as long as 

geowebcache-**miss-reason**

is empty


I'll double check the layer anyway

**Comment by randomorder** [comment]
fixed (associated tile layer was misaligned with GS config)
