### ISSUE TITLE
Review MEDIATORE:V_ELEMENTO_STRADALE configuration

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2-C040#355]
The MEDIATORE:V_ELEMENTO_STRADALE  layer sometimes does not respond properly to tile cache requests.
We get these response headers:

> geowebcache-cache-result: MISS

Please, double check GWC configuration for this layer.

**Comment by randomorder** [comment]
looks ok
![image](https://user-images.githubusercontent.com/5264230/99822630-c017d780-2b53-11eb-85dd-4d56eff1eb9e.png)
