### ISSUE TITLE
Review URBANISTICA:V_AER_PIANO_RISCHIO configuration

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2-C040#358]
The URBANISTICA:V_AER_PIANO_RISCHIO layer does not respond properly to tile cache requests.
We get these response headers:

> geowebcache-cache-result: MISS
> geowebcache-miss-reason: not a tile layer

Please, double check GWC configuration for this layer.

**Comment by randomorder** [comment]
looks ok to me
![image](https://user-images.githubusercontent.com/5264230/99827453-ed678400-2b59-11eb-9026-338b7b267c2d.png)

can you please let me know the name of the map that is including the layer?

**Comment by ElenaGallo** [comment]
@randomorder here the [SUE - SPORTELLO UNICO EDILIZIA ](https://mappe.comune.genova.it/MapStore2/#/viewer/openlayers/1000004003) map with this layer

**Comment by randomorder** [comment]
it's ok
thanks
