### ISSUE TITLE
Review mappa "Settore Energia - DATI AD ACCESSO CONSENTITO DALLA RETE INTERNA"

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2-C040#360]
We are talking about [this](https://mappe.comune.genova.it/MapStore2/#/viewer/openlayers/97) map.
- SITGEO:V_SEAP_PUNTI_LUCE_TIPOLOGIE does not seem to be a tile layer --> enabled server side cached and tiling client side
- BASE-CARTOGRAFICA added thumb  and format to JPEG

**Comment by ElenaGallo** [comment]
@randomorder can you enable the server side chaced for the layer above (SITGEO:V_SEAP_PUNTI_LUCE_TIPOLOGI ) ? thx
