### ISSUE TITLE
Review URBANISTICA:V_BENI_TUTELA_AREA configuration

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2-C040#361]
The URBANISTICA:V_BENI_TUTELA_AREA layer does not respond properly to tile cache requests.
We get these response headers:

> geowebcache-cache-result: MISS
> geowebcache-miss-reason: not a tile layer

Please, double check GWC configuration for this layer.

**Comment by randomorder** [comment]
fixed
