### ISSUE TITLE
Upgrade GeoServer

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/MapStore2-C040#363]
We want to upgrade GeoServer for Comune di Genova

![image.png](https://images.zenhubusercontent.com/5cd59eb418690954352b7621/535d0127-eff5-41eb-9c82-5c25f3810a83)

**Comment by randomorder** [comment]
Take the chance to update the JDK version as well if possible

**Comment by tdipisa** [comment]
Closed in favor of #443
