### ISSUE TITLE
Layer L3627 needs attention

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2-C040#364]
This layers seem to be a raster layer, Black/White (the worst).
- cache for png8 is not allowed, but we need it as it gives us better quality
- it does not have overviews IMHO since it is slow
- I cached in [this](https://mappe.comune.genova.it/MapStore2/#/viewer/openlayers/1000005544) map as JPEG but this shoud be changed in that map once PNG8 is allowed.

**Comment by randomorder** [comment]
This one is coming from the Regione Liguria

Request URL: https://geoservizi.regione.liguria.it/geoserver/M1407/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fjpeg&TRANSPARENT=true&LAYERS=L3627&STYLES=&SRS=EPSG%3A3857&CRS=EPSG%3A3857&TILED=true&ms2-authkey=50202e94-774c-4705-be0c-7e0ed2fea1be&WIDTH=256&HEIGHT=256&BBOX=993069.8714810088%2C5528843.12992337%2C993375.6195941495%2C5529148.87803651
