### ISSUE TITLE
Layer ELEVATION_CS_50CM needs attention

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2-C040#365]
This layers seem to be a raster layer, Black/White (the worst).
- cache for png8 is not allowed, but we need it as it is an overlay
- it does not have overviews IMHO since it is super slow
- Once the format is fixed, we can adapt [this](https://mappe.comune.genova.it/MapStore2/#/viewer/openlayers/1000005544) map to use PNG8

**Comment by randomorder** [comment]
![image](https://user-images.githubusercontent.com/5264230/99838023-c5cbe800-2b68-11eb-8234-0309ea2881de.png)

- single 108MB GTiff on the NFS
- no compression
- no tiling
- no overviews

**Comment by randomorder** [comment]
fixed
