### ISSUE TITLE
GeoServer's layer groups with not advertised members are not queriable

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2-C040#37]
see https://osgeo-org.atlassian.net/browse/GEOS-8165

Blocked by #173

**Comment by tdipisa** [comment]
@offtherailz please check this after the latest GS upgrade

**Comment by offtherailz** [comment]
actually none of the layer groups in production contain layers that are not advertised. In test environment it works well.
Should we ask to set some of them not advertise or should we close this issue @tdipisa ? I think it is not needed to repeat this test in production

**Comment by tdipisa** [comment]
@offtherailz not needed I think. Please move in accepted column.
