### ISSUE TITLE
Monitor Services with GHC

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/MapStore2-C040#376]
Add al least 2-3 checks to for the services with at least one hitting a raster file and one hitting the DB

link to mapstore [here](https://mappe.comune.genova.it/MapStore2/)

**Comment by giacomoc92** [comment]
I made a check on the mapstore frontend http://monitoring.geo-solutions.it/resource/249?lang=en

one on geoserver running getcapatilities, checking rasters and jndi http://monitoring.geo-solutions.it/resource/250?lang=en

is it enough?

**Comment by randomorder** [comment]
yes, ok
thanks
