### ISSUE TITLE
Monitor machines w/ Prometheus

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/MapStore2-C040#377]
with node exporter on the geoFE, geoBE1, geoBE2, geoDB

VPN instructions [here](https://docs.google.com/document/d/1xyBMEjdN1ZjeyiyTuFaXvBI3UfvvJlhJvgq1GGAOgOc/edit)

**Comment by lpasquali** [comment]
@randomorder for some reason I can't put estimate, would you mind to put 1 for me? it is similar to a ticket of last week I couldn't move out of progress

**Comment by lpasquali** [comment]
https://prometheus.io/docs/instrumenting/pushing/

**Comment by lpasquali** [comment]
I should have inserted the machines this way:

- from here I added a piece in the docker compose https://github.com/prometheus-community/PushProx
- then I added as documented in prometheus [doc](url)

there is still some work to do:

![image](https://user-images.githubusercontent.com/1780406/100372544-acfc8000-3009-11eb-8e59-74d60d7fe1f5.png)

**Comment by randomorder** [comment]
> there is still some work to do as some metric are not collected right:
> 
> ![image](https://user-images.githubusercontent.com/1780406/100372544-acfc8000-3009-11eb-8e59-74d60d7fe1f5.png)

What does this mean?

**Comment by lpasquali** [comment]
> > there is still some work to do as some metric are not collected right:
> > ![image](https://user-images.githubusercontent.com/1780406/100372544-acfc8000-3009-11eb-8e59-74d60d7fe1f5.png)
> 
> What does this mean?

that applying what is documented with current versions of node-exporter on the host and push gateway as a proxy, we do not get correct numbers in the metrics as the screenshot shows, the CPU for example has meaningless numbers.

**Comment by lpasquali** [comment]
![Screenshot from 2020-11-30 14-55-11](https://user-images.githubusercontent.com/1780406/100618411-1b985100-331c-11eb-95d2-f62430884573.png)
I can't get reliable values for CPU, CPU cores (it says 22, which is likely to be the sum of all 4) I could try to make one push gateway per node but I think it is quite non-sense, also networking is unreliable, but I expected that from this kind of monitoring
