### ISSUE TITLE
Production Deploy

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#411]
### Description
Deploy of the new MS's version in production environment (from #330). Needed actions are:

- [x] Align the **production** branch to the **master** one and update the MS's configuration accordingly
- [x] Generate the WAR file for the deploy
- [x] Deploy activity and test (for devops)
- [ ] When tests are passed in production do a Tag release

**Comment by randomorder** [comment]
can you please point me to the war file @tdipisa

**Comment by tdipisa** [comment]
@MV88 can you please take care of point 1 and 2 in description?
