### ISSUE TITLE
Configura regole di accesso does not work

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2-C040#414]
### Description
Opening the *Configura regole di accesso* the page is moving and this error appears console:

> GET https://mappe.comune.genova.it/geofence/rest/rules/count 403 (Forbidden)

*Steps to reproduce*

- Open Geonova istance
- Login as admin
- Click on Manager options
- Click on *Configura regole di accesso*

*Expected Result*
The page works as axpected 

*Current Result*
The page is blocked and a 403 (Forbidden) error appears on console

### Other useful information (optional):
Test failed on Cucumber:

> https://studio.cucumber.io/projects/47740/test-runs/520242/folder-snapshots/5133370/scenario-snapshots/18226606/test-snapshots/24288841

> https://studio.cucumber.io/projects/47740/test-runs/520242/folder-snapshots/5133370/scenario-snapshots/18226607/test-snapshots/24288842

**Comment by offtherailz** [comment]
@ElenaGallo This **must** work only in VPN. Outside this tool will not work. 

Moreover I remember that https://mappe.comune.genova.it/geofence/rest/rules/count fails only the first time (bug in geofence API) after a GeoServer reboot, but this error should be known by the application and recovered automatically with a retry. I think this is not your case, anyway.

**Comment by tdipisa** [comment]
@offtherailz I have the same issue on my local machine (windows). I think it is a problem related to the VPN client in windows. In VPN I cannot access geoserver/web as well (with the same error, Forbidden). I will ask the client to do a check.
