### ISSUE TITLE
Pluggable Data Editor issue

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#424]
### Description
Below the client feedback about this functionality:

>Pluggable Data Editor: STEP 5 nonostante il localConfig.json sia configurato come dovrebbe non si riesce a richiamare nel campo cod_controllo del datagrid la via e il civico con l'autocomplete. Abbiamo utilizzato la feature SITGEO:V_VINC_SOPRAINT e controllare

### Please indicate if this issue is related to a bug or a new feature request
- [X] Bug
- [ ] New Feature

### Other useful information (optional):
@ElenaGallo I saw [our test](https://studio.cucumber.io/projects/47740/test-runs/520242/folder-snapshots/5133362/scenario-snapshots/18226582/test-snapshots/24288817) on this is passed: can you please explain what have you tested?

**Comment by ElenaGallo** [comment]
@tdipisa below the test that I did following the hip test. The autocomplete works.
![Uploading genova.gif…]()

**Comment by ElenaGallo** [comment]
in the test instance the SITGEO:V_VINC_SOPRAINT. @tdipisa do you know if it is possible to test the issue with another layer?

**Comment by MV88** [comment]
@ElenaGallo you can use [this](http://vm-linuxgeofetest.comune.genova.it/MapStore2/#/viewer/openlayers/1000002552) map to check it in test env

**Comment by ElenaGallo** [comment]
@MV88 thank you. The issue passes the test. @tdipisa  I also modified the hiptest.
