### ISSUE TITLE
Feature Viewer Issue

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#425]
### Description
Below is reported the client test feedback about this functionality:

>Nel featureviewer e nel wmsfeatureviewer non si riesce a interrogare nessun elemento mentre prima era possibile interrogare le feature (es. https://mappe.comune.genova.it/MapStore2/#/wmsfeatureviewer/openlayers/SITGEO:V_SEZIONI_VIGILI/ID_PK%3E0)

### Please indicate if this issue is related to a bug or a new feature request
- [X] Bug
- [ ] New Feature

**Comment by MV88** [comment]
[this ](https://github.com/geosolutions-it/MapStore2/pull/6746) is the fix made in master that will be bakported in the custom branch

C040_2021_01

**Comment by MV88** [comment]
@ElenaGallo you can use this 
http://vm-linuxgeofetest.comune.genova.it/MapStore2/#/wmsfeatureviewer/openlayers/MEDIATORE:V_SOTTOPASSO/IDENTIFICATIVO%3E156
url to check this in test env
