### ISSUE TITLE
GeoServer GeoCollect under HTTPS

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#426]
### Description
We have to restore the functionalities of the viewer here where layers are no longer available on the map:
https://mappe.comune.genova.it/MapStore2/#/viewer/openlayers/geocollect

It seems the problem is due to the fact that the GeoServer is not under HTTPS: mixed content issues:

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/1461f026-a37b-4db8-b054-892c8a8b6797) 

### Other useful information (optional):
Related GeoServer is:
http://geocollect.geo-solutions.it/geoserver/web/

GeoServer Deploy Doc is:
https://docs.google.com/document/d/1nwfNaiH9fjM4sx54qrN0DdpboQ6Y1jOv9dEp_F_n_j4/edit

**Comment by randomorder** [comment]
Can you please set up HTTPS on the machine @lpasquali ?
It's an old Debian system with apache 2.2

**Comment by tdipisa** [comment]
Hi @randomorder any news about this?

**Comment by lpasquali** [comment]
hello @tdipisa I'm on it

**Comment by lpasquali** [comment]
@randomorder @tdipisa 

Installation log:

https://docs.google.com/document/d/1nwfNaiH9fjM4sx54qrN0DdpboQ6Y1jOv9dEp_F_n_j4/edit?ts=60755903#heading=h.jar9mekfr3zu

Result:
https://geocollect.geo-solutions.it/
https://geocollect.geo-solutions.it/geoserver/

**Comment by tdipisa** [comment]
@lpasquali thank you so much. I'm going to check.
