### ISSUE TITLE
GeoCollect review 

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#432]
### Description
The client required to review the GeoCollect context:
https://mappe.comune.genova.it/MapStore2/#/viewer/openlayers/geocollect

- [ ] Images modals cannot be closed

![geocollect_close.gif](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/990b74a8-085e-4dac-b4d8-dbb952b4dc6e)

- [ ] Some URL present in geocollect.json is still under HTTP but https must be used instead since we have installed the certificate with this #426 

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/6ec1dd36-90e6-4445-94bd-96d69e150a42)

**Comment by MV88** [comment]
1) the modals requires a new deploy since the problem was present in some custom components hence a new build is needed

2) fixed on the test server
