### ISSUE TITLE
GeoServer Update (production)

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#444]
### Description
The same GS (and GeoFence) update provided in test environment with #443 must be provided also for production environment.

### Other useful information (optional):
Deplyment documentations for production machien are:
- https://docs.google.com/document/d/1lTsj_CWCAawzLs_wUKMmtGQ2nbd6DWnFBe1u-cZWuZ4/edit#heading=h.na7bp1ac85tu
- https://docs.google.com/document/d/1vLCa3yVNFtO70TdAparkNK3io0B7fHGI6a4LftaRYZE/edit#heading=h.o890dgcn72a

**Comment by drumbsd** [comment]
Both GeoServer and GeoFence have been updated and also the documentation.
