### ISSUE TITLE
MapStore deploy (Production)

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#447]
### Description
Deploy and tests in production environment of the updated MS project (depends on #446).

Specific tests needed during the depoy:
- [ ] https://github.com/geosolutions-it/MapStore2-C040/issues/458
- [x] Test Run: https://studio.cucumber.io/projects/47740/test-runs/586387/overview

### Other useful information (optional):
Add also the new java_opts to the tomcat of MapStore in produciton as reported [here](https://github.com/geosolutions-it/MapStore2-C040/issues/445#issuecomment-904764019)

**Comment by drumbsd** [comment]
Update done and doc updated.
