### ISSUE TITLE
Link privacy

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#448]
### Description
The current privacy button in viewer should points to the following new URL:
https://smart.comune.genova.it/node/8227

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/e4be237f-7aeb-471e-a6b0-1091dd53c768)

**Comment by tdipisa** [comment]
@MV88 is it something we can configure in localconfig?
If not please move it back in backlog.

**Comment by MV88** [comment]
yes it is possible by change something inside localConfig.json
