### ISSUE TITLE
New source catalogs for Dashboards

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#454]
### Description
Include the possibility to define and add new catalog sources for Map and Table widgets in Dashboards. The catalog tool must be included for this in the context of Dashboards.

### Other useful information:
This new feature has been recently implemented through https://github.com/geosolutions-it/MapStore2/issues/6664

**The aim of this issue is to test this feature inside the c040 project as soon as updated** (see #445).

**Comment by ElenaGallo** [comment]
@MV88 @tdipisa this new feature is not present in the c040 project even if #445 has already been deploied

**Comment by tdipisa** [comment]
@MV88 it is probably a matter of configuration in localConfig. Let's check as soon as we can.

**Comment by MV88** [comment]
@tdipisa @offtherailz @ElenaGallo 
is not config related, the commits are **not backported** on branch **2021.01.xx**

do I need to backport the commits there?

**Comment by tdipisa** [comment]
>do I need to backport the commits there? 

@MV88, no. Let's move the issue in the next milestone. We will take care of this issue as soon as we release MS 2021.02.00.

**Comment by tdipisa** [comment]
@dsuren1 this feature has already been implemented in MS for 2021.02.00. Fro this iteration on c040 we have to raise a new PR to update the Ms project to the 2021.02.xx version where that feature is present and properly configure it if needed.
