### ISSUE TITLE
Install/Configure Grid Shift Transform files in GeoServer

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#463]
### Description
Install the Grid Shift Transform files in GeoServer for the CRS 7791 using the transform file provided by the client. Files are available at this path: \\vm-linuxgeofe\MapStore2\grigliati_GE.zip

The documentation to install Grid Shift Transform files is available in the [GeoServer online doc](https://docs.geoserver.org/stable/en/user/configuration/crshandling/coordtransforms.html#add-grid-shift-transform-files).

**Comment by tdipisa** [comment]
@randomorder yes. I'm taking care of this. The issue is in Blocked, the current status is reported in the email [here](https://groups.google.com/g/geosolutions-comunege/c/PcJa_FryPDA/m/x68FWN5GAAAJ)

**Comment by tdipisa** [comment]
I've collected few more precise feedback from the client that need to be investigated because it seems that GeoServer is introducing a not negligible offset for the Y coordinate.

From the client:

>abbiamo effettuato alcuni test e 'controtest' attraverso vari tools e trasformazioni planimetriche, e utilizzato un punto in epsg:3003 come es. che troverai sotto e in allegato come geojson

>1) il tool verto che ha realizzato l'IGM e che utilizza i grigliati (e che forse utilizza OGR2OGR)
http://212.77.67.76/vol/index_coord.php
--epsg:3003 1493588.5943154, 4917168.27707082
--epsg:7791 493561.462128087, 4917149.63929917

>2)  tool PCN
--Roma 1940 Italia zona 1 1493588.5943154, 4917168.27707082
--ETFRS89-ETFR2000 UTM Zona 32 493561.46211907;4917149.63930246
>3) in locale ogr2ogr -s_srs "+proj=tmerc +lat_0=0 +lon_0=9 +k=0.9996 +x_0=1500000 +y_0=0 +ellps=intl +nadgrids=d:\GK2\44080835_44400922_R40_F00.gsb +units=m +no_defs" -t_srs EPSG:7791 c:\GK2\N\CIVICI_7791.geojson c:\GK2\N\CIVICI_3003.geojson
--epsg:3003 1493588.5943154, 4917168.27707082
--epsg:7791 493561.462128086946905, 4917149.639299174770713

>4) convergo che ha realizzato il CISIS (con utilizzo grigliati)
--epsg:3003 1493588.5943154, 4917168.27707082
-- epsg:7791 493561.462 4917149.639

>4) geoserver CGE nella console che tu ci hai suggerito (e anche se scarichi via MS lo stesso punto. lO trovi qui in allegato)
--epsg:3003 1493588.5943154, 4917168.27707082
--epsg:7791 493561.49231676786 4917150.400064188

>Come noterete nei valori in Geoserver abbiamo quasi uguale la x, mentre un 76 cm come 'slittamento' sulla y che non sono trascurabili

>![image](https://user-images.githubusercontent.com/1280027/141279461-5985dafb-e246-4baa-b935-d953185b2f48.png)

>Non conosciamo quali librerie utilizzi Geoserver, ma è necessario trovare la soluzione a questo problema

>Rimaniamo disponibili anche a un meeting solo su questo argomento

@nmco it would be possible to involve @aaime for this? He his is also already aware of the topic because I've asked to him few days ago for the setup in GeoServer.

**Comment by aaime** [comment]
This is going to be challenging... GeoTools reads the grids with an external library, and the actual grid shift code was written by an external developer years ago. I'd say at least 4 hours just to look into it and get an idea, the actual fix might take days (just a gut feeling).

**Comment by tdipisa** [comment]
Ok @aaime. I will inform the client about the investigation time in the meeting today.

**Comment by tdipisa** [comment]
@aaime @nmco we can proceed with the investigation. @aaime please let me know when you can next days

**Comment by tdipisa** [comment]
Hi @simboss, @aaime we should proceed with this investigation as soon as possible. Please let me know about the scheduling.

**Comment by aaime** [comment]
I saw this ticket at the top of my list and picked it, but I cannot find the grid shift files. Any clue?

**Comment by aaime** [comment]
Matteo Velludini was kind enough to download the files and share them with me:

![image](https://user-images.githubusercontent.com/325433/144865263-3da22d34-c778-4696-82eb-291750bc7032.png)

**Comment by simboss** [comment]
@aaime this ticket is asking for an investigation and estimate first.
Just a reminder :)

**Comment by aaime** [comment]
It will still take a few hours just to reproduce and try to figure out what is going on.

**Comment by aaime** [comment]
I have setup the grids with both GeoServer main, and GeoServer 2.19.1. In both cases, I cannot reproduce the issue, the transformation on the reference point given above is less than a millimeter away from the transformation made with Convergo.

I have setup [a record of what I did here.](https://docs.google.com/document/d/1z1Yn4893mVQhCIqc_QIMwQ5W0B6vrCWRWvkwkD9lCNk/edit)

Since the issue might be related to setup of the grids, I've also shared the data directory used to make the tests, so that you can try it out as well:
[genova_data_dir.zip](https://github.com/geosolutions-it/MapStore2-C040/files/7661836/genova_data_dir.zip)

**Comment by tdipisa** [comment]
It seems gsb files in test where out of date. Updating them using the ones available in production machine (see description) the problem seems solved. Waiting the client feedback for confirmation.

**Comment by tdipisa** [comment]
We can move the config to production.
