### ISSUE TITLE
Error loading layers on GeoFence

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2-C040#465]
### Description
There is an error loading a layer on GeoFence, it could be a problem related to the new MS version or maybe the new GS version, or both: in PROD it works fine.

It seems that the CSW request made by MS to retrieve the list of layers is failing with this error:
![image](https://user-images.githubusercontent.com/1280027/126494682-c976eed3-ed69-4923-8459-dbbb29ab73ca.png)

**How to Reproduce**

Steps in the gif below or on [Cucumber test](https://studio.cucumber.io/projects/47740/test-runs/566300/folder-snapshots/5667893/scenario-snapshots/19999065/test-snapshots/27091529):
![GEOF3](https://user-images.githubusercontent.com/56537133/126487352-e2ceac1c-f602-4742-89ef-08791ae79b5f.gif)

*Current Result*
It is not possible to add a layer in a GeoFence rule

### Other useful information
The request sent by MapStore is the following one.

**URL:** http://vm-linuxgeofetest.comune.genova.it/geoserver-test/csw?service=CSW&version=2.0.2&request=&ms2-authkey=af12271c-4187-4ca8-bd3c-c7c7d03b4d58

**Method:** POST

**Payload:**
```
<csw:GetRecords xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dct="http://purl.org/dc/terms/" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gmi="http://www.isotc211.org/2005/gmi" xmlns:ows="http://www.opengis.net/ows" service="CSW" version="2.0.2" resultType="results" startPosition="1" maxRecords="5">
	<csw:Query typeNames="csw:Record">
		<csw:ElementSetName>full</csw:ElementSetName>
		<csw:Constraint version="1.1.0">
			<ogc:Filter>
				<ogc:PropertyIsLike wildCard="%" singleChar="_" escapeChar="\\">
					<ogc:PropertyName>identifier</ogc:PropertyName>
					<ogc:Literal>SITGEO:%%%</ogc:Literal>
				</ogc:PropertyIsLike>
			</ogc:Filter>
		</csw:Constraint>
	</csw:Query>
</csw:GetRecords>
```

**Copied as cURL (bash):**

```
curl 'http://vm-linuxgeofetest.comune.genova.it/geoserver-test/csw?service=CSW&version=2.0.2&request=&ms2-authkey=af12271c-4187-4ca8-bd3c-c7c7d03b4d58' \
  -H 'Connection: keep-alive' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36' \
  -H 'Content-Type: application/xml' \
  -H 'Origin: http://vm-linuxgeofetest.comune.genova.it' \
  -H 'Referer: http://vm-linuxgeofetest.comune.genova.it/MapStore2/' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  --data-raw '<csw:GetRecords xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dct="http://purl.org/dc/terms/" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gmi="http://www.isotc211.org/2005/gmi" xmlns:ows="http://www.opengis.net/ows" service="CSW" version="2.0.2" resultType="results" startPosition="1" maxRecords="5"><csw:Query typeNames="csw:Record"><csw:ElementSetName>full</csw:ElementSetName><csw:Constraint version="1.1.0"><ogc:Filter><ogc:PropertyIsLike wildCard="%" singleChar="_" escapeChar="\\"><ogc:PropertyName>identifier</ogc:PropertyName><ogc:Literal>SITGEO:%%%</ogc:Literal></ogc:PropertyIsLike></ogc:Filter></csw:Constraint></csw:Query></csw:GetRecords>' \
  --compressed \
  --insecure
```

**Comment by tdipisa** [comment]
@offtherailz, I've updated the description with more info. Can you please do a quick investigation to check why this problem occurs in the new version?

**Comment by offtherailz** [comment]
new versions of GeoServer look to require "dc:identifier" instead of "identifier"
The code that performs the request uses ogc-schemas, anyway the identifier string is passed by mapstore, here: 
https://github.com/geosolutions-it/MapStore2/blob/3815a91e052a72b54249e837f7d00905cd2b2cc6/web/client/api/CSW.js#L284

So it seems it is possible to change it from "identifier" to "dc:identifier" to make it work.

**Comment by offtherailz** [comment]
Need to wait for https://github.com/geosolutions-it/MapStore2-C040/issues/465 to be merged and update MapStore revision.
