### ISSUE TITLE
Increase GS Memory? 

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#494]
From the client:

>- recentemente con i sistemisti è stato effettuato un aggiornamento delle macchine virtuali:
a) https://vm-linuxgeofe.comune.genova.it/geoserver-master/
RAM VM aumentata a 12 gb (attualmente GS ha 4gb)
b) http://vm-linuxgeobe1.comune.genova.it:8080/geoserver/
RAM VM aumentata a 8 gb (attualmente GS ha 2gb)
c) http://vm-linuxgeobe2.comune.genova.it:8080/geoserver
RAM VM aumentata a 8 gb (attualmente GS ha 2gb)
Ci siamo chiesti se conviene aumentare anche la RAM utilizzabile in GS.
Voi cosa consigliate?
Nel caso riuscite a riconfigurarle o effettuamo la richiesta ai nostri sistemisti?

**Comment by randomorder** [comment]
Shouldn't be necessary to increase the heap unless they have specific needs. We should check the watchdogs and make sure they are working properly and wait for the invest. by GeoServer devs on logs and dumps

**Comment by tdipisa** [comment]
I'm sorry @randomorder, did you finally re-enable the watchdog that was inactive for the geobe1 server?

**Comment by tdipisa** [comment]
Ok, I was forgetting you mentioned it [here](https://github.com/geosolutions-it/MapStore2-C040/issues/491#issuecomment-965023987). Closing this.
