### ISSUE TITLE
Deploy in production

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2-C040#498]
After test passed on test env, deploy in production. We have to include also #507.

Additional activities:
- [x] Install the GS patch #491 
- [x] Move the GSB config to production #463

**Comment by tdipisa** [comment]
Additional activities already done @offtherailz.
@offtherailz did you already prepare the WAR file to deploy for production? I saw that the production branch is not yet updated. We should update it a produce the WAR to install since tomorrow we have to deploy it in production.

**Comment by offtherailz** [comment]
No @tdipisa  I prepared only the war for test env.
