### ISSUE TITLE
Problemi spazio vm-linuxgeodb1

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#506]
From the client:

>un nostro sistemista ci ha allertato rispetto al problema spazio nel db postgres che sembra essere arrivato al'1% libero
Ecco le note sotto, che ci ha inviato
Riuscireste a risolverlo?

>che c’è qualche problema di spazio per la macchina vm-linuxgeodb1. Prima di procedere noi ad un allargamento del disco c’è qualcosa che potete pulire voi direttamente o con l’ausilio di geosolutions? Il disco è sdb1.

> se hai modo di sentire geosolutions potresti chiedere loro di abilitare l’autovacuum del database postgres per liberare in automatico lo spazio (a meno ovviamente che non ci siano ragioni per averlo disabilitato).

**We already had the same problem in the past many time due to the GWC DB. It would be good to solve the issue once and for all this time. Is there a problem with the GWC disk quota also this time?**

**Comment by lpasquali** [comment]
For record, last time we had this issue we weren't able to catch enough data to understand the problem:

https://github.com/geosolutions-it/DevOps/issues/782

**Comment by lpasquali** [comment]
@tdipisa @randomorder I cleaned the gwc_geofe db truncating the tables, I also took a dump, but it is only 42Mb, which means a regular vacuum might help, but it should bve done before the disk is more than 50% full I think, anyway if they can enlarge the partition a bit it would not hurt.

**Comment by randomorder** [comment]
@FP-Geosolutions please sync with @lpasquali 
and check the autovacuum config for ComuneGS as you check the logs loration

**Comment by FP-Geosolutions** [comment]
Ok im working on it

**Comment by lpasquali** [comment]
Hello @FP-Geosolutions,

from what we see from the config, these commented values suggest autovacuum is enabled, but might be tuned.

```
[root@vm-linuxgeodb1 pgdata]# grep autovacuum  postgresql.conf
#autovacuum_work_mem = -1		# min 1MB, or -1 to use maintenance_work_mem
#autovacuum = on			# Enable autovacuum subprocess?  'on'
#log_autovacuum_min_duration = -1	# -1 disables, 0 logs all actions and
#autovacuum_max_workers = 3		# max number of autovacuum subprocesses
#autovacuum_naptime = 1min		# time between autovacuum runs
#autovacuum_vacuum_threshold = 50	# min number of row updates before
#autovacuum_analyze_threshold = 50	# min number of row updates before
#autovacuum_vacuum_scale_factor = 0.2	# fraction of table size before vacuum
#autovacuum_analyze_scale_factor = 0.1	# fraction of table size before analyze
#autovacuum_freeze_max_age = 200000000	# maximum XID age before forced vacuum
#autovacuum_multixact_freeze_max_age = 400000000	# maximum multixact age
#autovacuum_vacuum_cost_delay = 20ms	# default vacuum cost delay for
					# autovacuum, in milliseconds;
#autovacuum_vacuum_cost_limit = -1	# default vacuum cost limit for
					# autovacuum, -1 means use
[root@vm-linuxgeodb1 pgdata]#
```
docs on autovacuum: 

https://www.postgresql.org/docs/9.4/routine-vacuuming.html

from the docs what we mostly need is to implement: [23.1.2. Recovering Disk Space]()
in a way that vacuum starts before disk is too empty and necessary dump tables cannot be done anymore, thus failing.

**Comment by FP-Geosolutions** [comment]
@afabiani @lpasquali

**Comment by FP-Geosolutions** [comment]
probaly they already added some space:

```
[root@vm-linuxgeodb1 /]# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2        18G  3.1G   14G  20% /
devtmpfs        2.9G     0  2.9G   0% /dev
tmpfs           2.9G  4.0K  2.9G   1% /dev/shm
tmpfs           2.9G  305M  2.6G  11% /run
tmpfs           2.9G     0  2.9G   0% /sys/fs/cgroup
/dev/sda1       477M  193M  255M  44% /boot
/dev/sdb1        20G   11G  8.3G  56% /var/pgdata
tmpfs           581M     0  581M   0% /run/user/995
tmpfs           581M     0  581M   0% /run/user/0
tmpfs           581M     0  581M   0% /run/user/1000
You have mail in /var/spool/mail/root
```

**Comment by randomorder** [comment]
please check again the disk space usage in 1 month
