### ISSUE TITLE
3D Tiles Support (8dd)

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#519]
### Description

 * **Adding 3DTiles layer support in MapStore, for the Cesium mapType**: we can easily support tilesets hosted on a url (pointing to a tileset.json file) through the internal CesiumJS support and the "special" layers supported by Cesium, using a name instead:

```json
{
  "title": "Delft CityGML",
  "type": "3dtileset",
  "url": "http://localhost:8003/tilesets/TilesetDelft/tileset.json",
  "visibility": true,
  "zoomTo": true
}
```

```json
{
  "title": "Buildings",
  "type": "3dtileset",
  "name": "OSMBuildings",
  "visibility": false
}
```
 * **Catalog UI**: a new service type for 3Dtiles is needed; the configuration would allow setting:
     * a layer type: custom or one of the predefined ones, currently OSM Buildings
     * a url when custom is selected, to enter the link of a tileset.json file
 
![image](https://user-images.githubusercontent.com/2770528/113149549-6e830600-9233-11eb-82a9-a13de5d215c3.png)

This integration will require some initial work to make the Catalog Plugin more pluggable (currently all type of services are hardcoded).

**Comment by tdipisa** [comment]
From the client:

>qui la 3dtiles mesh
https://www.cityexplorer3d.com/Genova3D/dataset/tileset.json
(https://www.cityexplorer3d.com/Genova3D/)

>In questo senso avrei solo alcune note che magari affronteremo appena iniziato lo svilluppo:
2a. impostazione quota/elevazione 3Dtiles
2b. integrazione 3Dtiles con il dtm già presente

**Comment by offtherailz** [comment]
Remember to update `proxy.properties` aligning with the standard MapStore's one.

**Comment by tdipisa** [comment]
Tested with this map 
https://vm-linuxgeofetest.comune.genova.it/MapStore2/#/viewer/cesium/1000003517?center=8.891434864314538,44.407023232486985&zoom=20.16697261008597&heading=6.268211887013274&pitch=-0.3138062762669007&roll=3.2196991739397163e-9
