### ISSUE TITLE
3D Tiles Styling (5dd)

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#520]
### Description
 * **Adding support for styling**: the 3DTileset specification includes a JSON based styling specification, that is quite sophisticated and is supported (obviously) by CesiumJS. We could support the same as a layer option. 

```json
{
  "title": "Buildings",
  "type": "3dtileset",
  "name": "OSMBuildings",
  "visibility": false,
  "style": {
    "show" : "true",
    "color" : "color('${cesium#color}')"
  }
}
```

 * **Styling UI**: the simplest way to have a styling UI is to try reusing the text-editor MS already has for CSS and SLD styles to support the 3DTiles Styling (JSON based) language. 

Notice that 3DTiles has an "intrinsic style", such as color of buildings or point clouds, that cannot be read or changed by the Cesium library.  Therefore, we cannot expect to use the styler in the same ways we use the SLD/CSS styler for WMS,  for example, to get the intrinsic style and change it. We will only be able to, either, use the default style or use a custom one defined by the user in the 3DTiles styling language.

## Other useful information
_**For this issue we don't foresee supporting other styling languages for now (like css or sld) that would require converters and a not trivial effort to be implemented.**_ 

_**To enable a visual editor, we would require the above mentioned converters aimed to use the existing visual style editor for example.**_

**Comment by tdipisa** [comment]
From the client:

>vi inviamo un il link a un subsample 3dtiles degli edifici estrusi e a una nuvola punti .LAS 
Potete utilizzare questo come caso uso nello styling

>https://geoportale.comune.genova.it/sites/default/files/field/image/aa5/tileset.json
(https://geoportale.comune.genova.it/sites/default/files/field/image/tiles.html)

>https://geoportale.comune.genova.it/sites/default/files/field/image/LAS3930_4326_RGB/tileset.json
(https://geoportale.comune.genova.it/sites/default/files/field/image/tiles.html)

**Comment by MV88** [comment]
@ElenaGallo please check this TEST env

**Comment by ElenaGallo** [comment]
@MV88 Test passed on TEST env .
