### ISSUE TITLE
3D Zoom to via share URL (3dd)

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#521]
### Description
Update the Share Tool to provide the possibility to zoom to a specified location of the Cesium map through specific 3D viewer parameters.
The URL must contain the data necessary to replicate the exact position in cesium, so camera position (x,y,z) and  orientation ( heading,  pitch,  roll )

**Comment by dsuren1** [comment]
**Investigation:**
3D map (cesium) customized advanced setting options

- Center and zoom with orientation options (get default value from map and update on Share tool open)
  - _Pitch_:  -90 to 0 convert to radian (negative y-axis)
  - _Roll_:  0 to 360 convert to radian (positive x-axis)
  - _Heading_: 0 to 360 (positive z axis) 

**Code change**
[queryparam epics](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/epics/queryparams.js#L65) - add `viewerOptions` to `changeMapView` to supply 3D map with orientation information

[readQueryParamsOnMapEpic](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/epics/queryparams.js#L125) - after intercepting `LOCATION_CHANGE` listening to action type `LAYER_LOAD` will not work for 3d map hence we may have to listen to first `CHANGE_MAP_VIEW` as we dont need wait for final bbox bounds for 3d 

Needs vector support for marker in cesium map. So we can either hide this option from share tool or add support for vector layer (Kindly correct me if present already)

**Mock up**
![share_3d](https://user-images.githubusercontent.com/26929983/146767459-42a18bfb-4344-4ce0-a789-063ab7f8923b.jpg)

**Comment by tdipisa** [comment]
@dsuren1 ok for me? @offtherailz do you have any feedback?

**Comment by offtherailz** [comment]
Ok. @dsuren1 
about the option of adding marker, hide marker option at the moment. If possible, bbox should still be still an option, just the 3D specific parameters has precedence in 3D context.

 `viewerOptions` in `changeMapView` should already allow to include the parmeter you need, please check.

**Comment by dsuren1** [comment]
Hi @offtherailz 
> Ok. @dsuren1 about the option of adding marker, hide marker option at the moment.

Sure

> If possible, bbox should still be still an option, just the 3D specific parameters has precedence in 3D context.

The [bbox](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/map/cesium/Map.jsx#L401) is always maintained a constant limits -180,-90,180, 90. I think we can modify bounds with value `computeViewRectangle()` and convert value to degree, which can later be used for getting values for bbox option?

> `viewerOptions` in `changeMapView` should already allow to include the parmeter you need, please check.

I meant, the viewerOption value is not passed as parameter [here](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/epics/queryparams.js#L65)

**Comment by offtherailz** [comment]
> The bbox is always maintained a constant limits -180,-90,180, 90. I think we can modify bounds with value from computeViewRectangle() and convert value to degree, which can later be used for getting values for bbox option?
Ok. I checked. I didn't remember. So I'm agree with you. 

In 3d hide the options like bbox or point, that doesn't have an implementation.

> I meant, the viewerOption value is not passed as parameter here and should be passed for applying orientation data to 3d map
Yes correct.
