### ISSUE TITLE
logs and audits rotation issue

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/MapStore2-C040#525]
Looks like audits files at `/var/lib/tomcats/geoserver/logs/audits` and localhost_access files at `/var/lib/tomcats/geoserver/logs/localhost_access_log.*` are not compressesed / rotated correctly on the production machines

I manually Gzipped them on `linuxgeobe1` and `linuxgeobe2` to prevent filling the root FS

**Comment by randomorder** [comment]
VPN Doc [here](https://docs.google.com/document/d/1Jim7mUpU5METiUj5b0M62BzUPM_ZfEV2PtSwJZ0f7o8/edit?usp=sharing)

**Comment by FP-Geosolutions** [comment]
Moved to blocked, waiting new VPN credential expired on 14/01/2021

**Comment by tdipisa** [comment]
@randomorder is this still in progress? The VPN was reset over two weeks ago.

**Comment by randomorder** [comment]
yes it is. We'll get back to you next week
