### ISSUE TITLE
Heavy CPU use for GeoServer on vm-linuxgeobe1

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#526]
### Description
The client is reporting again problems with _vm-linuxgeobe1_:

> Ciao, vi segnaliamo che  la macchina vm-linuxgeobe1 ha un carico anomalo di cpu causato da geoserver, iniziato alle 21:20 del 5 gennaio. Procediamo con il solito riavvio di geoserver?

With [#491](https://github.com/geosolutions-it/MapStore2-C040/issues/491#issuecomment-986712856) we installed a patch to fix issues previously reported as part of the ticket [#48562]( http://geosolutions.freshdesk.com/helpdesk/tickets/48562).

**Comment by randomorder** [comment]
GeoServer restarted. I was not able to retrieve logs and dumps unfortunately
I'll try again is we face the same issue in the future
