### ISSUE TITLE
GeoServer GeoCollect not responding

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#532]
From the client:

>Buongiorno,
oggi mi ha chiamato un collega che vorrebbe visualizzare il livello in Geocollect, ma in questo momento la mappa si apre ma non si visualizza il livello.
Ho ritrovato email sotto in cui segnalavate che sareste intervenuti. In effetti nella issue #503. sembrerebbe tutto risolto.
Tuttavia l'errore rimane

>Riuscireste a ricontrollare se il motivo è lo stesso e nel caso risolvere il problema?

Accessing this:
https://mappe.comune.genova.it/MapStore2/#/viewer/openlayers/geocollect

Geocollect layers are not loaded in the map. It seems the geoserver is down: 
https://geocollect.geo-solutions.it/geoserver/

**Comment by randomorder** [comment]
Problem is related to Apache Startup  (details below)

Service is back now with a temporary workaround but will become unavialable again on reboot (requires a manual intervention) **BUT** we need to talk about future of machine and create a separate task for a proper fix asap @tdipisa

**Comment by tdipisa** [comment]
Thank you @randomorder, I've opened #533. Please put there your comments if necessary.
