### ISSUE TITLE
Test deploy for few updates - v1.3.2-test

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#534]
To deploy:
https://github.com/geosolutions-it/MapStore2-C040/pull/530
https://github.com/geosolutions-it/MapStore2-C040/pull/531

Tag to use for this deploy is v1.3.2-test generated from the latest commit containing the above PRs commits.

**Comment by tdipisa** [comment]
@offtherailz we need a war of master for a deploy in test.

**Comment by offtherailz** [comment]
You can download it from here.
https://drive.google.com/file/d/1ZqidyTjTTmL3fN6YPDzfbHY7xsnUsDxs/view?usp=sharing
