### ISSUE TITLE
GetFeatureInfo not working when performed to GeoServer Geocollect

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#535]
## Description

Accessing to 
https://mappe.comune.genova.it/MapStore2/#/viewer/openlayers/geocollect

and performing Identify requests, we obtain HTTP 400:

https://mappe.comune.genova.it/MapStore2/proxy/?url=https%3A%2F%2Fgeocollect.geo-solutions.it%2Fgeoserver%2Fit.geosolutions%2Fows%3Fservice%3DWMS%26version%3D1.1.1%26request%3DGetFeatureInfo%26exceptions%3Dapplication%252Fjson%26id%3Dcens_muri__8%26layers%3Dcens_muri%26query_layers%3Dcens_muri%26x%3D51%26y%3D51%26height%3D101%26width%3D101%26srs%3DEPSG%253A3857%26bbox%3D989821.2977788901%252C5526473.582046527%252C997541.4376356929%252C5534193.72190333%26feature_count%3D10%26info_format%3Dapplication%252Fjson%26ENV%3D

Without passing through the proxy the request works:

https://mappe.comune.genova.it/MapStore2/proxy/?url=https%3A%2F%2Fgeocollect.geo-solutions.it%2Fgeoserver%2Fit.geosolutions%2Fows%3Fservice%3DWMS%26version%3D1.1.1%26request%3DGetFeatureInfo%26exceptions%3Dapplication%252Fjson%26id%3Dcens_muri__8%26layers%3Dcens_muri%26query_layers%3Dcens_muri%26x%3D51%26y%3D51%26height%3D101%26width%3D101%26srs%3DEPSG%253A3857%26bbox%3D989821.2977788901%252C5526473.582046527%252C997541.4376356929%252C5534193.72190333%26feature_count%3D10%26info_format%3Dapplication%252Fjson%26ENV%3D

But the requests also works passing through the proxy to gs-stable:

https://mappe.comune.genova.it/MapStore2/proxy/?url=https%3A%2F%2Fgs-stable.geo-solutions.it%2Fgeoserver%2Fwms%3Fservice%3DWMS%26version%3D1.1.1%26request%3DGetFeatureInfo%26exceptions%3Dapplication%252Fjson%26id%3Dgs%253Aus_states__9%26layers%3Dgs%253Aus_states%26query_layers%3Dgs%253Aus_states%26x%3D51%26y%3D51%26height%3D101%26width%3D101%26srs%3DEPSG%253A3857%26bbox%3D-8237026.151324235%252C4978228.996671102%252C-8233166.081395833%252C4982089.066599504%26feature_count%3D10%26info_format%3Dtext%252Fhtml%26ENV%3D

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by randomorder** [comment]
@FP-Geosolutions please retrieve a copy of the mapstore and tomcat logs while the requests are triggered 
[geofe](https://docs.google.com/document/d/1Y-aGsvpALGwGOhowzYYY1yY5kdl4eO-UvRS1HadDNwQ/edit)

I am gessing some sort of issue with the proxy, maybe SSL handshake

**Comment by randomorder** [comment]
I repeat what I said on Thursday @FP-Geosolutions: grabbing the MapStore logs from the production machine is a 10m task and should be performed pretty much immediately! We can't have clients waiting 10 days on a proble on a production system for no reason

**Comment by FP-Geosolutions** [comment]
It's seems a cross origin problem 

```
Request URL: https://mappe.comune.genova.it/MapStore2/proxy/?url=https%3A%2F%2Fgeocollect.geo-solutions.it%2Fgeoserver%2Fit.geosolutions%2Fows%3Fservice%3DWMS%26version%3D1.1.1%26request%3DGetFeatureInfo%26exceptions%3Dapplication%252Fjson%26id%3Dcens_muri_sop__7%26layers%3Dcens_muri_sop%26query_layers%3Dcens_muri_sop%26x%3D51%26y%3D51%26height%3D101%26width%3D101%26srs%3DEPSG%253A3857%26bbox%3D995019.0157022818%252C5525632.774735391%252C1002739.1555590846%252C5533352.914592193%26feature_count%3D10%26info_format%3Dapplication%252Fjson%26ENV%3D
Request Method: GET
Status Code: 400 400
Remote Address: 93.62.175.66:443
Referrer Policy: strict-origin-when-cross-origin
```

**Comment by randomorder** [comment]
We need mapstore logs

**Comment by FP-Geosolutions** [comment]
The production `/etc/httpd/virtualhost.conf` is set with test cors 

```
 ServerAlias sitgeofe
    #DocumentRoot "/www/default"
    Header add Access-Control-Allow-Origin "http://vm-linuxgeofetest.comune.genova.it"
    #Header add Access-Control-Allow-Origin "https://mappe.comune.genova.it"
    #Header add Access-Control-Allow-Origin " http://mappe.comune.genova.it"
    Header always set Access-Control-Request-Headers: Content-Type
    Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"
    #Header always set Access-Control-Allow-Headers "Access-Control-Request-Method, X-Requested-With, Content-Type, Origin, Authorization, Accept, Client-Security-Token, Accept-Encoding"
    Header always set Access-Control-Allow-Headers "*"
```

Here the logs of `catalina.out` : 

```
14-Mar-2022 11:03:28.503 WARNING [ajp-nio-0.0.0.0-7009-exec-5] it.geosolutions.httpproxy.ProxyConfig.mergePropertiesConfig The properties file ${datadir.location}/proxy.properties cannot be found
14-Mar-2022 11:03:28.503 WARNING [ajp-nio-0.0.0.0-7009-exec-2] it.geosolutions.httpproxy.ProxyConfig.mergePropertiesConfig The properties file ${datadir.location}/proxy.properties cannot be found
14-Mar-2022 11:03:28.576 WARNING [ajp-nio-0.0.0.0-7009-exec-5] it.geosolutions.httpproxy.ProxyConfig.mergePropertiesConfig The properties file ${datadir.location}/proxy.properties cannot be found
14-Mar-2022 11:03:28.577 WARNING [ajp-nio-0.0.0.0-7009-exec-2] it.geosolutions.httpproxy.ProxyConfig.mergePropertiesConfig The properties file ${datadir.location}/proxy.properties cannot be found
```

in mapstore.log there is this recurring error, but dosen't seems related to this issue:

```
ERROR   2022-03-14 11:05:49.091   UserAttributeTokenAuthenticationFilter.checkToken() - No users matching the given token.
INFO   2022-03-14 11:05:49.096   TokenAuthenticationFilter.authenticate() - User authenticated using token: User[id=1000010340, name=b105445, group=[UserGroup[id=1000004128, groupName=COA_TELECAMERE-SIT], UserGroup[id=69, groupName=everyone], UserGroup[id=1000002975, groupName=AIRWATCH_USERS_POLIZIA_MUNICIPALE], UserGroup[id=208, groupName=POLIZIA MUNICIPALE (TUTTI)], UserGroup[id=290, groupName=PM_DISTRETTO2], UserGroup[id=1000015038, groupName=PL_SICUREZZA_STRADALE]], role=USER]
INFO   2022-03-14 11:06:07.927   BaseMapServlet.getMapPrinter() - Loading configuration file: /var/lib/tomcats/mapstore2/webapps/MapStore2/printing/config.yaml
WARN   2022-03-14 11:06:07.930   CustomBeanWrapper.setProperty() - AddressHostMatcher: unknown field 'host' with value '127.0.0.1' 
```

**Comment by FP-Geosolutions** [comment]
@randomorder To fix `virutalhosts.conf` can I proceed directly or we need to advise the customer?

**Comment by FP-Geosolutions** [comment]
Then probably miss some entry point in` /var/lib/tomcats/mapstore2/webapps/MapStore2/configs/localConfig.js`

```json
 "proxyUrl": {
    "url": "/MapStore2/proxy/?url=",
    "useCORS": [
      "https://nominatim.openstreetmap.org",
      "https://mappe.comune.genova.it",
      "http://vm-linuxgeofetest.comune.genova.it",
      "http://www.realvista.it/",
      "http://192.168.153.1:8080",
      "http://192.168.153.11:8080",
      "https://appaltige.comune.genova.it"
    ]
  },:
```

**Comment by randomorder** [comment]
I did not understand your comments and you did not state if the problem is fixed or not and how you eventually fixed it

**Comment by randomorder** [comment]
Error is on the geoserver side

Does not like the URL when going trough the proxy for some reason:
```
==> ./catalina.out <==
Mar 14, 2022 2:05:03 PM org.apache.jk.common.HandlerRequest invoke
SEVERE: Error decoding request
java.io.CharConversionException: Invalid char in port: 45
        at org.apache.jk.common.HandlerRequest.parseHost(HandlerRequest.java:703)
        at org.apache.jk.common.HandlerRequest.decodeRequest(HandlerRequest.java:432)
        at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:281)
        at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:776)
        at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:705)
        at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:898)
        at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:690)
        at java.lang.Thread.run(Thread.java:745)

Mar 14, 2022 2:05:03 PM org.apache.jk.common.ChannelSocket processConnection
WARNING: processCallbacks status 2
```

Try adding GeoCollect to the No proxy hosts in localConfig.json @FP-Geosolutions 
both the plain HTTP and HTTPS URLs. If CORS is configured properly on the GeoCollect machine a direct request should work

**Comment by tdipisa** [comment]
We have sorted this in test by reverting the http-proxy version to 1.1.1 we are scheduling a production deploy with the client. Hopefully tomorrow we will do it.

**Comment by tdipisa** [comment]
Deploy in production succeeded:

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/b535e962-57e2-4757-b496-1dbdbc2fd262)

We can close.
