### ISSUE TITLE
feature loader crashes because of wrong parameter passed to orientateMap

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2-C040#540]
## Description

this issue is caused by [this](https://github.com/geosolutions-it/MapStore2/issues/7853)

basically here 

https://github.com/geosolutions-it/MapStore2/blob/e0dfd9b1acebaff7ddbd848e6fcb072fdfc35d2a/web/client/epics/queryparams.js#L197-L207

it take the search params and it passes to the orientate map action

if I understood the issue well we should pass these params to the orientate Map only if we are in 3D mode
and moreover if we find them among the search params

so a dedicated issue should be fixed on mapstore side

Also I think that PR could have broke other queryparams actions (this have to be verified)

## How to reproduce

-  open this project 
-  load http://localhost:8081/?debug=true#/featureviewer/openlayers/CULTURA:V_BANCA_TERRA/INCLUDE?_k=hsp0ve

*Expected Result*

to load map 
![image](https://user-images.githubusercontent.com/11991428/159059102-f4de95b9-8f15-4736-b7ab-9c85b2634dd8.png)

*Current Result*

crash

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by MV88** [comment]
this project is aligned to 2022.01.xx [here](https://github.com/MV88/MapStore2-C040/tree/538_update_2022.01.xx)

**Comment by tdipisa** [comment]
@MV88 of course we need to fix this MS side so please open an issue on MS ans assign this to me. Anyway, the final part of the URL (_?_k=hsp0ve_) is not related to the FW functionalities so this issue is not blocking the release.

**Comment by MV88** [comment]
@tdipisa ok i've opened this in mapstore project
https://github.com/geosolutions-it/MapStore2/issues/7991
