### ISSUE TITLE
Tomcat update in Test Environment

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#546]
- At least 8.5 is needed for the latest MS version.

- Production version of Tomcat to check to schedule also the update there if necessary as part of the deployment in production activities (scheduled for 30-03-2022)

**Comment by randomorder** [comment]
Hi @tdipisa 
Taking a quick look today to estimate the effort. We can then tackle it on Monday or Tuesday max depending on other activities to perform

**Comment by tdipisa** [comment]
@randomorder Is that a peculiar tomcat installation? Keep me updated please. It would be good, if possible, to have the tomcat updated by Monday morning to allow us to execute a complete test run and so to be able to apply patches on Tuesday (if needed) before the release (scheduled for next Wednesday).

**Comment by randomorder** [comment]
> @randomorder Is that a peculiar tomcat installation?

Yes,
Tomcat 8 is not available in the repositories for `CentOS Linux release 7.2.` and would have required a full manual setup of CataBase and CataHome + startup scripts and documentation while makeing sure not to break the existing tomcat7 installation used by other applications on the machine.
Not a trivial task and, as you know, today we are understaffed

Now,
I had a look at the system and found that **GeoServer** is already running on Tomcat8 so we already have a base installation..
I moved on and updated the catalina base and configuration files for MapStore and now is running on Tomcat 8.5.69 hope this version is new enough

Moving to Test

FYI @MV88

**Comment by randomorder** [comment]
By the way it looks like all applications are running on tomcat8 now we can probably get rid of tomcat7

**Comment by MV88** [comment]
> Tomcat 8.5.69 hope this version is new enough
yes it is

@randomorder 
so can I try to do a new release?

@tdipisa you agree to do it now??

**Comment by randomorder** [comment]
> so can I try to do a new release?

Nothing has changed in that regards. The usual procedure should work

**Comment by tdipisa** [comment]
> > Tomcat 8.5.69 hope this version is new enough
> 
> yes it is
> 
> @randomorder so can I try to do a new release?
> 
> @tdipisa you agree to do it now??

Yes @MV88 you can

@randomorder 
>Yes,
Tomcat 8 is not available in the repositories for CentOS Linux release 7.2. ...

I was imaging. Thank you so much

**Comment by tdipisa** [comment]
I've verified for production https://github.com/geosolutions-it/MapStore2-C040/issues/548#issuecomment-1081828678
We can close.
