### ISSUE TITLE
cubotti_tot tileset not visible in cesium map

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#564]
## Description

The client is asking to check why the following tileset _**cubotti_tot**_ available in this map is not visible while _**cubotti_sub**_ yes instead:

https://mappe.comune.genova.it/MapStore2/#/viewer/cesium/1000015684?center=8.892779234048698,44.40055778629244&zoom=18.712350668358482&heading=0.5763283349716781&pitch=-0.1667647960911285&roll=6.28317862296175

## How to reproduce

-  Open the provided link and activate the _**cubotti_tot**_ layer in TOC

*Expected Result*

The layer should be visible.

*Current Result*

The layer is not visible.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

cubotti_sub: https://geoportale.comune.genova.it/sites/default/files/field/image/aa5/tileset.json
cubotti_tot: https://geoportale.comune.genova.it/sites/default/files/field/image/bb_tot/tileset.json
cagliari: https://www.cityexplorer3d.com/tourism/ca-dataset/tileset.json

**Comment by allyoucanmap** [comment]
# Issue

The tileset.json contains tiles with invalid bounding volume region exent where the minimun x is equal to maximum x and the minimum y is equal to the minimum y similar to this https://github.com/geosolutions-it/MapStore2-C040/issues/563#issuecomment-1092653496

# Solution

Provide tilesets with valid bounding volume regions where the limit value on the x and y axis are not the same.
See specification https://github.com/CesiumGS/3d-tiles/tree/1.0/specification#region

# Investigation

We initially tested the tileset.json in the Cesium sandcastle to understand if it was an issue MapStore side but we got an error also there. The error was the same found here https://github.com/geosolutions-it/MapStore2-C040/issues/563#issuecomment-1092653496

![image](https://user-images.githubusercontent.com/19175505/162411979-5cf38419-3b8e-47bb-8dfa-36ffc51a79a7.png)

```
Error
    at new DeveloperError (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:83:13)
    at Function.Cartesian3.normalize (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:2126:13)
    at computeBox (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:217978:39)
    at new TileBoundingRegion (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:217867:5)
    at createRegion (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:220882:12)
    at Cesium3DTile.createBoundingVolume (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:220941:14)
    at new Cesium3DTile (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:219353:33)
    at makeTile (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:225514:12)
    at Cesium3DTileset.loadTileset (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:225435:29)
    at https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:224314:27
```

we tried to intercept the tileset json response and we noticed that some region extent had x and y limits whit same value meaning the region has a width and height equal to 0

`[minx, miny, maxx, maxy, minimum height, maximum height]`

![image](https://user-images.githubusercontent.com/19175505/162416962-44a49c9d-ee2a-426d-92ec-6f19afc80f8f.png)

to confirm that those were causing the issue we apply on the fly a small delta value when a region was incorrect to validate it

`[minx - delta, miny - delta, maxx + delta, maxy + delta, minimum height, maximum height]`

and we finally got a working tileset 

![image](https://user-images.githubusercontent.com/19175505/162417299-48979764-81e4-4811-bf61-0e6abffe61a6.png)
