### ISSUE TITLE
Update to latest revision to include 3d tiles (v1.4.1)

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2-C040#565]
## Description

The MapStore revision need to be updated to the stable branch **2022.01.xx**

### Checks

It is necessary to check if the existing customizations are properly working after the project update. Custom or client's specific extensions are the following **that will be checked during the PR review**:

- [x] **Thematic Maps / Statistical Query Engine Update**: Not officially maintained. It is necessary to check it after the update (a reference map [here](https://mappe.comune.genova.it/MapStore2/#/viewer/openlayers/1000002291) in production environment). Hiptest available [here](https://studio.cucumber.io/projects/47740/test-runs/421040/folder-snapshots/4008457/scenario-snapshots/14592539/test-snapshots/19053266).

- [x] **Integration with SPID** (italian authentication system for Public Administrations): to check after the update. Hiptest available [here](https://studio.cucumber.io/projects/47740/test-runs/421040/folder-snapshots/4008465/scenario-snapshots/14592553/test-snapshots/19053280).

- [x] **GeoCollect embedded**: to check after the update. Hiptests are available [here](https://studio.cucumber.io/projects/47740/test-runs/421040/folder-snapshots/4008459/scenario-snapshots/14592543/test-snapshots/19053270) and [here](https://studio.cucumber.io/projects/47740/test-runs/421040/folder-snapshots/4008464/scenario-snapshots/14592549/test-snapshots/19053276)

- [x] **FeatureViewer**: to check after the update. Hiptest available [here](https://studio.cucumber.io/projects/47740/test-runs/421040/folder-snapshots/4008466/scenario-snapshots/14592554/test-snapshots/19053281)

- [x] **Public Works Plugin**: to check after the update. Hiptest is available [here](https://studio.cucumber.io/projects/47740/test-runs/421040/folder-snapshots/4008466/scenario-snapshots/14592555/test-snapshots/19053282)

- [x] **test internal login**: to check after the update
  - load and see if using admin user it works /internal-login.html

### Notes

Remember to update the project following [migration guidelines](https://mapstore.readthedocs.io/en/latest/developer-guide/mapstore-migration-guide/)

In particular in the **master** branch
- [x] update version in package.json to be aligned to the new release version (e.g. v1.4.1 without -test)
- [x] update version present in version.txt in this case use what will be the new tag

**Comment by MV88** [comment]
@ElenaGallo please check this TEST env

**Comment by ElenaGallo** [comment]
@MV88 test passed on TEST env
