### ISSUE TITLE
Query panel breaks if WPS is not available

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2-C040#58]
If the query panel is configured to use WPS to autocomplete the values and there is any issue with the WPS service (service unavailable, cors not allowing connection, network error) the query panel becomes unusable.

In this case the user cannot input values to create filters.

**Comment by Gnafu** [comment]
Main issue --> https://github.com/geosolutions-it/MapStore2/issues/2019

**Comment by MV88** [comment]
closed by #59
