### ISSUE TITLE
Editing feature in MS2 per utenti LDAP e SPID

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#80]
E' necessario abilitare l'editing delle features catalogate in Geoserver, tramite MS2, non solo loggandosi come amministratore ma anche loggandosi come utenti con autenticazione LDAP e SPID. Le regole verranno definite in geofence, come concordato nel meeting

**Comment by MV88** [comment]
see https://github.com/geosolutions-it/MapStore2/issues/2304
