### ISSUE TITLE
Statistical Query Engine: Thematics Maps

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#90]
**Thematic maps** : Several spatial aggregator levels, ability to create themas using the GeoServer sldService

**Comment by offtherailz** [comment]
I suggest some changes. 
 - Change the button and tooltip of the configuration panel. "Tooltip" should change from "Back to thema" to "Use this configuration". Icon from back arrow to `ok`
Old: 
![image](https://user-images.githubusercontent.com/1279510/42286386-0225d522-7fb3-11e8-9e2a-f3c31076ad3e.png)
New:
![image](https://user-images.githubusercontent.com/1279510/42286284-a6ee6da4-7fb2-11e8-88f1-23f5ee41b508.png)
 - Change tooltip for gear from "back to configuration" into "Configure..." 
![image](https://user-images.githubusercontent.com/1279510/42286427-28d9868c-7fb3-11e8-9e48-3a742223da8d.png)
 - Change icons and tooltips of Classification
Old: 
![image](https://user-images.githubusercontent.com/1279510/42286455-401ba000-7fb3-11e8-846b-44641863f425.png)
New icons (`trash`, `reset`, `ok`): 
![image](https://user-images.githubusercontent.com/1279510/42286252-8b4f8844-7fb2-11e8-8c9f-d52f62fe2b2a.png)
Alternative (`reset`, `clear-brush`, `ok`) : 
![image](https://user-images.githubusercontent.com/1279510/42286987-f12e7fa6-7fb4-11e8-9e7f-8a12227e8239.png)

Tooltip should be:
- Remove classification
- Reset customizations
- Apply classification

Is difficult to understand that you have to click to "apply" button on every change. To improve the user experience I suggest 2 possible solutions: 
 1. Maybe the easier: the should be disabled until the user have changes to be applied. This way the user understand that he have to click there see the classification on the map. Seeing the button change from grayed to colored may suggest the user he have to click there to see the changes applied

 2. Place an initial + button near classification, with nothing else. 
![image](https://user-images.githubusercontent.com/1279510/42286908-a50bf2de-7fb4-11e8-9fdb-7b1254bdf8b1.png)


When the user click on "+" the panel with classifications appears. 

The current default classification is applied automatically and all the changes are applied directly to the map, without the apply button. 
![image](https://user-images.githubusercontent.com/1279510/42286999-03c7dc20-7fb5-11e8-8f98-24af4c8a20d2.png)

When the user click on the "remove classification" button (can be x or trash), the panel disappears again and you back to the Classification with only the "+" button. 
![image](https://user-images.githubusercontent.com/1279510/42286908-a50bf2de-7fb4-11e8-9fdb-7b1254bdf8b1.png)

**Comment by offtherailz** [comment]
- [ ] Classificando punti, la legenda viene visualizzata senza colori ![image](https://user-images.githubusercontent.com/1279510/42518920-3084a5c4-8463-11e8-839c-60896afb4f3c.png)

**Comment by mbarto** [comment]
Anche per il punto 2 servono dei passi per riprodurre. Io ho provato in vari modi ma non sono riusciti a far salvare quei parametri.

**Comment by mbarto** [comment]
Per il punto 1: va modificato SLD service che sui punti non ritorna un size e la GetLegendGraphic di GS non usa un size di default (a differenza di GetMap)
