### ISSUE TITLE
Going to Home with print tool opened it messes up the layout

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2-C040#95]
## steps to reproduce
- open a map
- open print tool
- clik home button

![image](https://user-images.githubusercontent.com/11991428/32655205-fb550f84-c60c-11e7-9284-16434ab07f01.png)
![image](https://user-images.githubusercontent.com/11991428/32655226-01394f32-c60d-11e7-8c51-9e93d511a2cc.png)

**Comment by allyoucanmap** [comment]
Related issue [#2428](https://github.com/geosolutions-it/MapStore2/issues/2428)
